### ISSUE TITLE
Refresh Token randomly is invalid

### ISSUE THREAD

**Issue by mr-jakkopp** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#107]
I run a little private website to have my Fortnite XP progress displayed. I am using the EpicAPI to connect to the QueryProfile which generally works very well. I automated this process to update my stats every 5 minutes using Google App Script to fetch my website. I run into the following issue though. Out of nowhere, rather than getting my auth key and refresh token extended, I get the following response:

May 22, 2023, 6:49:20 PM:
`{"errorCode":"errors.com.epicgames.account.auth_token.invalid_refresh_token","errorMessage":"Sorry the refresh token 'MY_REFRESH_TOKEN' is invalid","messageVars":["MY_REFRESH_TOKEN"],"numericErrorCode":18036,"originatingService":"com.epicgames.account.public","intent":"prod","error_description":"Sorry the refresh token 'MY_REFRESH_TOKEN' is invalid","error":"invalid_grant"}`

I usually recieve the following (success message):

May 22, 2023, 6:44:20 PM
`{"access_token":"MY_TOKEN","expires_in":7200,"expires_at":"2023-05-22T11:14:20.132Z","token_type":"bearer","refresh_token":"MY_REFRESH_TOKEN","refresh_expires":28800,"refresh_expires_at":"2023-05-22T17:14:20.132Z", and so on`

As you can see, these responses were only 5 minutes apart but produces these results. Is there a way of avoiding this issue? Or is there a workaround? Is there any information on this in the docs that I missed or by Epic Games?

**Comment by LeleDerGrasshalmi** [comment]
Is this a fortnite client authentication?
If so fortnite invalidates all other fortnite sessions on launch so you would need to create a new session instead of trying to refresh a invalidated one

**Comment by LeleDerGrasshalmi** [comment]
Also you should ONLY request a new access token (refreshing) when the current token expired

**Comment by mr-jakkopp** [comment]
I'll change the overly excessive refreshing. Do you mean that once I launch Fortnite (e.g. to actually play), it kills all other active tokens? I have played with my "tracker" before and it did update (my database) every 5 minutes with the current level and xp which is when the website is called. Could it be that it kills all active tokens on close instead?

**Comment by LeleDerGrasshalmi** [comment]
#### Do you mean that once I launch Fortnite (e.g. to actually play), it kills all other active tokens?
> **Yes**, on launch, **NOT** on close

#### If this is the case, how could I generate a new token programmatically without any manual input?
 > How do you currently store the authentication data?
 > Only the current session, or also other stuff? How do you authenticate in general? 
> You should use an **Launcher Refresn Token** (Lasts ~20 Days)

**Comment by mr-jakkopp** [comment]
**How do you currently store the authentication data? 
Only the current session, or also other stuff? How do you authenticate in general?**
I currently store the epic, auth key, refresh key and the expiry time of the auth key in a database.

I am using the fortnitePCGameClient to authenticate and then refresh here "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token".

**You should use an Launcher Refresn Token (Lasts ~20 Days)**
Will try the Launcher Refresh Token. Is this one going to be invalidated on game launch as well?

**Comment by mr-jakkopp** [comment]
Thanks for your help. Ran into the issue with the Launcher one saying:
`{ "errorCode" : "errors.com.epicgames.common.missing_action", "errorMessage" : "Login is banned or does not posses the action 'PLAY' needed to perform the requested operation for platform ''", "messageVars" : [ "PLAY", "" ], "numericErrorCode" : 1023, "originatingService" : "fortnite", "intent" : "prod-live" }`

Found a workaround though. I am now using the device auth (pretty sure that's the one you use on your discord server too) with iOS. Seems to be working fine. Generating a new auth key every time the old one invalidates due to game launch or expiry_time.

Thanks again for your help!

**Comment by LeleDerGrasshalmi** [comment]
You obviouly need to exchange the launcher token to a fortnite token first.

**Comment by mr-jakkopp** [comment]
Obvious... 😅 Whoops. Will check again today. Thanks for your help.
