### ISSUE TITLE
How to see linked accounts?

### ISSUE THREAD

**Issue by 2ir** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#114]
how to see the linked accounts of another player? (xbl, psn, nintendo)

**Comment by LeleDerGrasshalmi** [comment]
GET `https://account-public-service-prod.ol.epicgames.com/account/api/public/account`
use the `accountId` Query Parameter (can be used up to 100 times)

**Comment by 2ir** [comment]
Thankss
