### ISSUE TITLE
Refactoring - Missing Examples, Permissions and more

### ISSUE THREAD

**Issue by LeleDerGrasshalmi** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#115]
### If you think that more stuff should be refactored, just leave a comment.

# Fortnite Service

- [ ] [Missing APIs like granting Access](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/Fortnite)
- [ ] [include response when entitlement not owned](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/EntitlementCheck.md)
- [x] [Move the Fortnite Service into the new Directory](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/FN-Service)

---

# Friends Service

- [x] [Missing Permissions, Permissions and APIs, Parameter Explanation, also there are multiple APIs in one File.](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/FriendsService)

---

# Stats Proxy

Include Example reponses when the User has Stats private.

- [X] [Single](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/StatsProxyService/Stats/UserStats.md)
- [X] [Bulk](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/StatsProxyService/Stats/UserStatsBulk.md)

---

# Needs Examples

- [X] [Account Service - Account - Device Auth](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Account/DeviceAuth)
- [X] [Account Service - Account - External Auth](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Account/ExternalAuth)
- [X] [Account Service - Account - Device Code](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/AccountService/Authentication/DeviceCode)
- [X] [Account Service - Account - Exchange Code](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/ExchangeCode)
- [X] [Account Service - OAuth - Kill Session(s)](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Kill)
- [X] [Account Service - OAuth - Create Session](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Token.md)
- [ ] [Account Service - Corrections](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Corrections)
- [X] [Global Service - Profile](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/GlobalService/Profile)
- [X] [Global Service - Reboot Rally](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/GlobalService/RebootRally)
- [ ] [Web - Fortnite APIs](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/Web/Fortnite)

---

# Affiliate Web APIs

This is not a high priority.

- [X] [Fully remake these: Structure, remove obsolete APIs, Add examples etc.](/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/Web/Affiliate)

**Comment by martiibear** [comment]
Don't you think MCP operations should also have a example?

**Comment by LeleDerGrasshalmi** [comment]
The descriptions explain what the value is supposed to be and sometimes when its like an Enum Shows the value.
So no these should not have examples and the response is just the full profile do.

**Comment by LeleDerGrasshalmi** [comment]
Finally got arround to completely rework the friends service !

**Comment by LeleDerGrasshalmi** [comment]
FN Service & DAD Service have now been moved into their own directories inside the services dir
