### ISSUE TITLE
QueryPublicProfile error

### ISSUE THREAD

**Issue by 2ir** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#122]
What does this mean on QueryPublicProfile?

`{
  "errorCode" : "errors.com.epicgames.modules.profiles.profile_not_found",
  "errorMessage" : "Read-only (true) or non-allow-create (! true) operation could not be applied to account cf7d49c474f2424b8738d793658d3c74 profile campaign because it was not found.",
  "messageVars" : [ "cf7d49c474f2424b8738d793658d3c74", "campaign" ],
  "numericErrorCode" : 12804,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}`

**Comment by LeleDerGrasshalmi** [comment]
As the error says "errors.com.epicgames.modules.profiles.**profile_not_found**" and the message says "... profile campaign **because it was not found.**"

The Account doesnt has that profile.

**Comment by 2ir** [comment]
> 

so it doesn't have save the world?

**Comment by LeleDerGrasshalmi** [comment]
Yes. But even if you have the profile(s) doesnt mean that the account owns StW, it just means the account called QueryProfile on the profile(s) before let it be the game or themself using the api.

**Comment by 2ir** [comment]
Ohh okay thank you
