### ISSUE TITLE
Last Activity

### ISSUE THREAD

**Issue by 2ir** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#123]
Is it possible to see the date of the last fortnite match someone played or just the last activity in fortnite?

**Comment by LeleDerGrasshalmi** [comment]
The `athena` Profile may have a `last_match_end_datetime` stat.
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/62852525/4cdb5c92-9ddd-475e-90a0-5f7fabb53791)

StW doesnt really has such a thing, but you could get the Accolade Tracker Item (`Token:stw_accolade_tracker`) and check the `last_update`, while that wont be totally when the last match ended, it was when you last received stw xp

**Comment by 2ir** [comment]
Can you do the first one with other peoples accounts too or just your own?

**Comment by LeleDerGrasshalmi** [comment]
only your own

**Comment by 2ir** [comment]
Do you know if there's a way to see it for other people?

**Comment by LeleDerGrasshalmi** [comment]
Probably using Stats, looking for lastModified
but Stats may take up to 1h or so to update

**Comment by 2ir** [comment]
okay thanks
