### ISSUE TITLE
QueryProfile not returning all Banners for Fortnite

### ISSUE THREAD

**Issue by 2ir** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#135]
Is there another endpoint where I can get the full list?

**Comment by LeleDerGrasshalmi** [comment]
Query Profile does return all Players the Player owns

**Comment by LeleDerGrasshalmi** [comment]
Which Profile are you requesting?

**Comment by 2ir** [comment]
> Which Profile are you requesting?

I'm requesting my own profile and it's not returning all banners. Other people have the same issue

**Comment by LeleDerGrasshalmi** [comment]
> Your own Profile
Which Profile???? (like athena, common_public, etc.)

**Comment by 2ir** [comment]
> > Your own Profile
> 
> Which Profile???? (like athena, common_public, etc.)

ohh💀 I used athena

**Comment by LeleDerGrasshalmi** [comment]
Banners are stored in **common_core**

**Comment by 2ir** [comment]
> Banners are stored in **common_core**

okay thank you
