### ISSUE TITLE
Fortnite V-Bucks

### ISSUE THREAD

**Issue by aharries43** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#138]
Is there an endpoint where you can see how many V-Bucks you have? (other than https://www.epicgames.com/account/v2/api/wallet/fortnite)

**Comment by LeleDerGrasshalmi** [comment]
VBucks are just Items in your `common_core` Profile, check the [QueryProfile](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/QueryProfile.md) MCP Operation.

VBucks Items a are `Currency:Mtx***` (*** = there are different variants of these items)

**Comment by aharries43** [comment]
> VBucks are just Items in your `common_core` Profile, check the [QueryProfile](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/QueryProfile.md) MCP Operation.
> 
> VBucks Items a are `Currency:Mtx***` (*** = there are different variants of these items)

Can you tell me how to calculate how much vbucks you have?

**Comment by LeleDerGrasshalmi** [comment]
just count the items, and if you have MtxDebt minus that

**Comment by aharries43** [comment]
> 

Can you give an example code? I can't seem to figure it out

**Comment by LeleDerGrasshalmi** [comment]
This repo is meant for people who know what they are doing!

**Comment by aharries43** [comment]
I got the response and all the data. I just don't know how to calculate the vbucks so would really appreciate the help

**Comment by noteason** [comment]
as Lele Said vbucks show up in items named Currency:Mtx... for things like different platforms, You can calculate how much total you have by using a very nice and easy to use thing called addition aka +, if you do not know how to use math then i reccomend you ask your teacher instead of people on github

**Comment by aharries43** [comment]
> as Lele Said vbucks show up in items named Currency:Mtx... for things like different platforms, You can calculate how much total you have by using a very nice and easy to use thing called addition aka +, if you do not know how to use math then i reccomend you ask your teacher instead of people on github

Ohh I'm so sorry, I thought you had to calculate the vbucks with the purchase history and packs bought etc. The account I tested it on had 0 vbucks so it didnt show this:

"templateId" : "Currency:MtxPurchased",
          "attributes" : {
            "platform" : "Live"
          },
          "quantity" : 10000
        }
