### ISSUE TITLE
How can I grab someone else's profile?

### ISSUE THREAD

**Issue by martiibear** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#139]
I have heard and seen you can get the cosmetics of another player's locker (not all of them). I was wondering how u could? (fortnite)

**Comment by aharries43** [comment]
@LeleDerGrasshalmi please dont share this, its getting abused

**Comment by LeleDerGrasshalmi** [comment]
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/QueryPublicProfile.md

**Comment by martiibear** [comment]
> @LeleDerGrasshalmi please dont share this, its getting abused

I don't mean any harm using this endpoint. I don't plan to use this publicly or sell software that uses this endpoint. This is just for testing and to see how the Epic API works! Sorry if it looks like I mean anything that goes against Epic Games' TOS.
