### ISSUE TITLE
PRM Dialog Service - Fortnite BR MOTD Issue

### ISSUE THREAD

**Issue by curtishdev** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#141]
Hello, everyone!

Really like you documentation, its useful, but unfortunately got some troubles with API endpoint :(

Endpoint: _https://prm-dialogue-public-api-prod.edea.live.use1a.on.epicgames.com/api/v1/fortnite-br/surfaces/motd/target_

While trying to access it, using access_token, post, got this error, with VPN/Without:

`{"errorCode":"errors.com.epicgames.forbidden","errorMessage":"Forbidden","messageVars":[],"numericErrorCode":1003,"originatingService":"prm-dialogue","intent":"prod"}`

Here is some of my code:
```
async def grab_fortnite_info(info: dict, session: aiohttp.ClientSession) -> dict:
    async with session.post(
        f"https://prm-dialogue-public-api-prod.edea.live.use1a.on.epicgames.com/api/v1/fortnite-br/surfaces/motd/target/",
        headers={
            "Authorization": f"bearer {info['access_token']}",
            "content-type": "application/json"
        },
    ) as resp:
        print("\nFortnite Info:\n")
        print((await resp.text())[:500])
        
        if resp.status != 200:
            return {}
        else:
            return await resp.json()
```
```
        fortnite_data = await grab_fortnite_info(info, session)
        if isinstance(fortnite_data, str):
            print(f"{fortnite_data}")
            return
```

**_I don't now another endpoints to access curent Battle Pass Tier and Lifetime Wins via Epic API, so help with this one please.
Appiciate any help, advices!_**

For Helpes: I'll provide any of needed code for causing this error

**Comment by LeleDerGrasshalmi** [comment]
Hi, as the docs say you need a EG1 Account token.

**Comment by curtishdev** [comment]
As I know, access_token is EG1 token) Can you explain, what type of token
do you mean? If the long one, than, it’s access_token or EG1 token type, if
short one, it’s different. Help please

**Comment by curtishdev** [comment]
> Hi, as the docs say you need a EG1 Account token.

Thanks a lot. Will test it. As I understood it's small one, time-limited code. I will try to change with it Authorization header and back with results.

**Comment by curtishdev** [comment]
Oh, have some troubles, maybe you can show me how to call it correctly?
Do I need launcher token? Store eg1 in data not in headers?
Can you show simple example, how to call it using auth_code: str (eg1 code)
Will appiciate this very much!

**Comment by curtishdev** [comment]
```
async def grab_fortnite_info(auth_code: str, session: aiohttp.ClientSession) -> dict:
    async with session.post(
        f"https://prm-dialogue-public-api-prod.edea.live.use1a.on.epicgames.com/api/v1/fortnite-br/surfaces/motd/target/",
        headers={
            "Authorization": f"bearer {auth_code}",
            "content-type": "application/json"
        },
    ) as resp:
        print("\nFortnite Info:\n")
        print((await resp.text())[:500])
        
        if resp.status != 200:
            return {}
        else:
            return await resp.json()
```


```
        fortnite_data = await grab_fortnite_info(authcode, session)
        if isinstance(fortnite_data, str):
            print(f"{fortnite_data}")
            return
```

`{"errorCode":"errors.com.epicgames.forbidden","errorMessage":"Forbidden","messageVars":[],"numericErrorCode":1003,"originatingService":"prm-dialogue","intent":"prod"}`

**_Really need your help, guys :)_**

**Comment by LeleDerGrasshalmi** [comment]
You have to use the eg1 with the bearer Scheme.

**Comment by LeleDerGrasshalmi** [comment]
Eg1 is a jwt...

**Comment by curtishdev** [comment]
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/54275918/08a5018a-657f-4540-afef-104f8eeba3b0)
Is it what do you mean? If yes, than I'm already using this type of auth, and its not woking :(

**Comment by curtishdev** [comment]
Thanks man, can you provide simple api to get all BP season levels and account info for Fortnite and headers + params for it
You're gonna help me a lot!

**Comment by LeleDerGrasshalmi** [comment]
Account info is in this repo and bp levels are in the gamefiles

**Comment by curtishdev** [comment]
> Account info is in this repo and bp levels are in the gamefiles 

So I can't get CurrentBP and something like this from API?

**Comment by curtishdev** [comment]
Do you know what endpoint is this?

  "_id": "0cfa707823534c17a32be0c5e1748da9",
  "created": "2019-09-29T11:52:26.138Z",
  "updated": "2023-08-20T18:55:25.045Z",
  "rvn": 9361,
  "wipeNumber": 5,
  "accountId": "ade36c23e6a84faf93e72ead547b546e",
  "profileId": "athena",
  "version": "season25_2530_StoriesQuestBundleFix_Aug_2023",
  "stats": {
    "attributes": {
      "past_seasons": [
        {
          "seasonNumber": 10,
          "numWins": 0,
          "numHighBracket": 0,
          "numLowBracket": 0,
          "seasonXp": 0,
          "seasonLevel": 1,
          "bookXp": 0,
          "bookLevel": 1,
          "purchasedVIP": false,
          "numRoyalRoyales": 0
        },

**Comment by LeleDerGrasshalmi** [comment]
Thats a Profile.
