### ISSUE TITLE
Permission - fortnite:stats READ

### ISSUE THREAD

**Issue by quikyy** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#146]
Hi!
I want to ask if you know how to get stats permission. I understand that an account without these permissions **_'fortnite:stats READ'_** cannot access player stats endpoints. Is that correct?

Cheers :)

**Comment by quikyy** [comment]
"Sorry your login does not posses the permissions 'fortnite:profile::accountId:commands ALL' needed to perform the requested operation"
"Sorry your login does not posses the permissions 'fortnite:stats READ' needed to perform the requested operation""

How to handle situation like these?

**Comment by quikyy** [comment]
thanks, solved it - works for me :)

**Comment by prestonwindfeldt** [comment]
> thanks, solved it - works for me :)

How were you able to find a client with the correct permissions?

**Comment by LeleDerGrasshalmi** [comment]
Fortnite clients have fortnite related perms

**Comment by prestonwindfeldt** [comment]
> Fortnite clients have fortnite related perms

I have a personal Fortnite account where I can access the account ID. I think in order to authenticate with the API I need the ID and a secret, so I feel like I am not on the right track. Is there another place I am able to create a Fortnite client?

**Comment by LeleDerGrasshalmi** [comment]
you cannot create a client with permissions

**Comment by LeleDerGrasshalmi** [comment]
and there are auth docs in this repo

**Comment by prestonwindfeldt** [comment]
> and there are auth docs in this repo

I try to authenticate with clients listed here:
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Clients.md

Then I see what permissions they have here:
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Permissions.md

And I want to use fornite related endpoints. Are these the auth docs?

**Comment by LeleDerGrasshalmi** [comment]
if you want to use fortnite related endpoints then oyu should use fortnite related endpoints
you can also search for clients which have a certain permission on https://egs.jaren.wtf

**Comment by prestonwindfeldt** [comment]
> if you want to use fortnite related endpoints then oyu should use fortnite related endpoints you can also search for clients which have a certain permission on https://egs.jaren.wtf

I don't see any auth docs in the fortnite directory and therefore, tried using auth under epic games. Am I missing something within the fortnite directory?

**Comment by LeleDerGrasshalmi** [comment]
why would there be auth docs in the fortnite directory...
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication

**Comment by prestonwindfeldt** [comment]
> why would there be auth docs in the fortnite directory... https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication

Yes, that is the auth I have been using. Do you happen to know what client would give you the roles required to use the endpoints in the fortnite/creative endpoints? I feel like I tried all of them in clients.md and the outside source you provided at the bottom of that doc?

**Comment by LeleDerGrasshalmi** [comment]
> you can also search for clients which have a certain permission on https://egs.jaren.wtf/
