### ISSUE TITLE
Need help grabbing skins

### ISSUE THREAD

**Issue by martiibear** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#155]
Used `QueryPublicProfile` but it only returns STW items. I thought it also returns skins that the account owner has? If so, please enlighten me on how I can achieve to get the skins.

**Comment by martiibear** [comment]
I also tried `QueryProfile` to be more specific:

`https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{accountID}/public/QueryProfile?profileId=campaign&rvn=-1`

Gave me error:

`
{
  "errorCode" : "errors.com.epicgames.modules.profiles.operation_forbidden",
  "errorMessage" : "Operation QueryProfile not allowed via this route",
  "messageVars" : [ "QueryProfile" ],
  "numericErrorCode" : 12813,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}
`

Please help!

**Comment by Jaren8r** [comment]
You can't use QueryProfile over the `/public/` route, you need to use the `/client/` route.

**Comment by martiibear** [comment]
i figured
