### ISSUE TITLE
Unable to get Account information with External Auth

### ISSUE THREAD

**Issue by martiibear** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#157]
```py
import requests

headers = {
    "Content-Type": "application/x-www-form-urlencoded",
    "Authorization": "basic zz"
}

body = {
    "grant_type": "authorization_code",
    "code": "no"
}

xbl_name = input('Xbox Name: ')
r = requests.get(f"https://account-public-service-prod.ol.epicgames.com/account/api/public/account/lookup/externalAuth/xbl/{xbl_name}/", headers=headers, data=body)
print(r.text)
```

Error:

```
{"errorCode":"errors.com.epicgames.common.not_found","errorMessage":"Sorry the resource you were trying to
 find could not be found","numericErrorCode":1004,"originatingService":"com.epicgames.account.public","int
ent":"prod"}
```

**Comment by LeleDerGrasshalmi** [comment]
That is completely wrong.
You are passing the authentication paylaod for /token to a get request

and you are also using a completely wrong url...
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/d75ca4764688556a7881203ebb1a664ec8f14bfb/EpicGames/AccountService/Account/Lookup/External/Displayname.md

**Comment by martiibear** [comment]
The URL is correct?

```py
import requests

body = {
    "grant_type": "authorization_code",
    "code": "no"
}

xbl_name = input('Xbox Name: ')
r = requests.get(f"https://account-public-service-prod.ol.epicgames.com/account/api/public/account/lookup/externalAuth/xbl/{xbl_name}/", data=body)
print(r.text)
```

I just switched the placeholders? E.g :externalAuthType with xbl and :displayName with the xbox uernme

**Comment by LeleDerGrasshalmi** [comment]
the url is not correct, i sent the documentation, and that you are sending the auth payload makes still no sense

**Comment by martiibear** [comment]
Found out the issue with the URL, still don't quite get the issue with trying to authenticate

**Comment by LeleDerGrasshalmi** [comment]
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/d75ca4764688556a7881203ebb1a664ec8f14bfb/EpicGames/AccountService/Authentication/Token.md

**Comment by martiibear** [comment]
Still not following.

**Comment by LeleDerGrasshalmi** [comment]
This is basic oauth2 authentication...
if you dont understand then i cannot help you

**Comment by martiibear** [comment]
I don't get why you can't just tell me specifically what's wrong?

**Comment by LeleDerGrasshalmi** [comment]
I told you this is basic oauth2 usage.
im not here to explain the very basics.

**Comment by martiibear** [comment]
This is the same way I authenticate with `QueryPublicProfile`. Why doesn't it work here?

**Comment by LeleDerGrasshalmi** [comment]
That is clearly not the same way you authenticate there, that would not work.
https://www.google.com/search?q=What+is+oauth2&ie=UTF-8&oe=UTF-8

**Comment by martiibear** [comment]
```json
{
	"errorCode": "errors.com.epicgames.common.unsupported_media_type",
	"errorMessage": "Sorry your request could not be processed as you are supplying a media type we do not support.",
	"numericErrorCode": 1006,
	"originatingService": "com.epicgames.account.public",
	"intent": "prod"
}
```

**Comment by LeleDerGrasshalmi** [comment]
What are you doing......

**Comment by martiibear** [comment]
Requesting it, using Insomnia to see

**Comment by LeleDerGrasshalmi** [comment]
requesting what

**Comment by martiibear** [comment]
https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token

**Comment by LeleDerGrasshalmi** [comment]
then use it with the correct parameters. as the the docs i sent mention?
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/d75ca4764688556a7881203ebb1a664ec8f14bfb/EpicGames/AccountService/Authentication/Token.md

**Comment by martiibear** [comment]
I'm incredibly sorry! I did not know I had to use password based authentication, I got the access token now

**Comment by martiibear** [comment]
```py
import requests

headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}

credentials = ("3446cd72694c4a4485d81b77adbb2141", "9209d4a5e25a457fb9b07489d313b41a")

body = {
    "grant_type": "authorization_code",
    "code": "no"
}

xbl_name = input('Xbox Name: ')
r = requests.get(f"https://account-public-service-prod.ol.epicgames.com/account/api/public/account/lookup/externalAuth/:xbl/displayName/:{xbl_name}/", data=body, auth=credentials)
print(r.text)
```

**Comment by LeleDerGrasshalmi** [comment]
Thats not how it works.
You first need an Access Token (bearer) from https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/d75ca4764688556a7881203ebb1a664ec8f14bfb/EpicGames/AccountService/Authentication/Token.md

then you need to include that in the `Authorization` Header like `Bearer ACCESS_TOKEN`.

and your lookup url should be like `https://account-public-service-prod.ol.epicgames.com/account/api/public/account/lookup/externalAuth/xbl/displayName/{xblName}`

**Comment by martiibear** [comment]
I got the access token, so it should be looking like this

```py
import requests

headers = {
    "Content-Type": "application/x-www-form-urlencoded",
    "Authorization": "Bearer (access token)"
}

credentials = ("3446cd72694c4a4485d81b77adbb2141", "9209d4a5e25a457fb9b07489d313b41a")

body = {
    "grant_type": "authorization_code",
    "code": "no"
}

xbl_name = input('Xbox Name: ')
r = requests.get(f"https://account-public-service-prod.ol.epicgames.com/account/api/public/account/lookup/externalAuth/xbl/displayName/{xbl_name}", headers=headers, data=body, auth=credentials)
print(r.text)
```

**Comment by LeleDerGrasshalmi** [comment]
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/62852525/bee44d3a-80c5-4c3a-a4c4-8791beaf1a23)

there is just everything wrong, i really dont think i can help you.
LEARN BASIC OAUTH2

**Comment by martiibear** [comment]
sorry, found out the issue was headers was only
