### ISSUE TITLE
authenticating by external_auth

### ISSUE THREAD

**Issue by 2ir** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#170]
I got the external_auth code for google. How do I use it?

**Comment by LeleDerGrasshalmi** [comment]
Hi, using the external auth grant type
<https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/GrantTypes/external_auth.md>

Main request docs - <https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Token.md>

**Comment by LeleDerGrasshalmi** [comment]
you need to combine them

so youi would need atleast these 3 fields:
- `grant_type` = `external_auth`
- `external_auth_type` - xatype
- `external_auth_token` - verification token from the third party

**Comment by Fynnstw** [comment]
Wie tue ich ein Fortnite rette die Welt bot programmieren
