### ISSUE TITLE
How do I fetch the last match played by the user?

### ISSUE THREAD

**Issue by malsvn** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#175]
Title

**Comment by LeleDerGrasshalmi** [comment]
You don't

**Comment by johngagefaulkner** [comment]
> _**Side note:**_
It's so crazy to me that Epic doesn't keep track of stats-per-match. I understand that the amount of data they store/process would increase exponentially considering they're already having to handle data for more than fifteen-million (15M+) monthly players on average but, I mean, this is a solved problem. Select your stack based on criteria that meets business' needs, configure your logging to meet a price-per-player projection model and then you're done ─ storage prices don't increase at scale, they decrease (and so, too, does CPU (per/ms) pricing.

**Comment by LeleDerGrasshalmi** [comment]
Oh, they do store data for each Match. But you just cannot get your hands on it ☹️

**Comment by LeleDerGrasshalmi** [comment]
Oh, they do store data for each Match. But you just cannot get your hands on it ☹️

**Comment by kennedybaird** [comment]
@LeleDerGrasshalmi - sorry to dig this up, but how does fortnitetracker.com get some match information then?

**Comment by LeleDerGrasshalmi** [comment]
Frequently fetching stats
