### ISSUE TITLE
something seems strange when trying to login through the api

### ISSUE THREAD

**Issue by TuNiman1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#176]
Response Content: {"errorCode":"errors.com.epicgames.accountportal.csrf_token_invalid","message":"Something went wrong. Please refresh the page and check that you allow cookies on your device. If the error persists, please contact <a href=\"https://www.epicgames.com/help/contact-us\" target=\"_blank\" rel=\"noopener noreferrer\">Player Support</a>.","correlationId":"bd553c00-7131-11ee-beed-31f90ffb6333"}

**Comment by TuNiman1** [comment]
@LeleDerGrasshalmi ?

**Comment by LeleDerGrasshalmi** [comment]
which api?
and as the error says, you dont provide none or an invalid xsrf token

**Comment by TuNiman1** [comment]
@LeleDerGrasshalmi

**Comment by LeleDerGrasshalmi** [comment]
password+email login is not intended to be used, therefore a captcha exists

**Comment by TuNiman1** [comment]
is there any way to bypass it?

**Comment by LeleDerGrasshalmi** [comment]
it is not intended to use that login method. NO

**Comment by TuNiman1** [comment]
hmm, thanks, so what is the use for the api login?

**Comment by LeleDerGrasshalmi** [comment]
Using OAuth 2
<https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/AccountService/Authentication>

Grant Types are in
<https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/AccountService/Authentication/GrantTypes>

**Comment by TuNiman1** [comment]
so how do i get a positive response and make what ive tried to make (type email and password in input-output conversation and check if they are valid)

**Comment by LeleDerGrasshalmi** [comment]
thus that sounds really suspicious

**Comment by TuNiman1** [comment]
no no dont think like that xD, i wanted to make an epic games login for my game lol

thanks anyways :)

**Comment by LeleDerGrasshalmi** [comment]
then use eos
https://dev.epicgames.com/docs/epic-online-services

**Comment by TuNiman1** [comment]
haha lol ill try, thanks :)
