### ISSUE TITLE
Redeem code

### ISSUE THREAD

**Issue by Ricoroma** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#187]
when im trying to get any of code redemption endoints, i get some error
in POSA - redeem - Forbidden 403
and on 'https://fulfillment-public-service-prod.ol.epicgames.com/fulfillment/api/public/accounts/{}/codes/{}' (not from this research) - i got that code is not found (but i know that it's valid)
so does anybody know, what is corrent endpoint for code redemption and what request is required?

**Comment by LeleDerGrasshalmi** [comment]
Maybe tell us what the error is??
But ig no perm, but Show the error response

**Comment by Ricoroma** [comment]
@LeleDerGrasshalmi 
sure
**Access token IS valid, content-type is application/x-www-form-urlencoded**

POSA Redeem
data={'code': 'code', 'platform': 'EPIC'},
POST

<ClientResponse(https://www.fortnite.com/:locale/api/posa/code/redeem) [403 Forbidden]>
<CIMultiDictProxy('Date': 'Thu, 16 Nov 2023 07:54:27 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'Permissions-Policy': 'accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'Referrer-Policy': 'same-origin', 'X-Frame-Options': 'SAMEORIGIN', 'cf-mitigated': 'challenge', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Set-Cookie': '__cf_bm=SLtPQj5mUGW8lnu1pmdHX0KtV5.U4QXML3EQOYy.dWg-1700121267-0-AfvkBY+WsxamOgycmfhXQC0rzPh4N3AEQCum8P82iwm4j6BJ3L8tgXS1YAvlt9AhfV64KktzI+99i7XwS3T3UyE=; path=/; expires=Thu, 16-Nov-23 08:24:27 GMT; domain=.fortnite.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '826e2a8458af09ba-MIA', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400')>

same with api/posa/code/status

EpicGames/Web/Fortnite/CodeRedemption/Redeem.md

<ClientResponse(https://www.fortnite.com/ajax/redemption/validate-redemption-code?hostPageId=code-redeem&redeem-code=LQU5H-S37XJ-WNLNK-EYS85) [403 Forbidden]>
<CIMultiDictProxy('Date': 'Thu, 16 Nov 2023 08:30:22 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'Permissions-Policy': 'accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'Referrer-Policy': 'same-origin', 'X-Frame-Options': 'SAMEORIGIN', 'cf-mitigated': 'challenge', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Set-Cookie': '__cf_bm=LtSVza4x_rw._9b4Uan7o1g0cpLF2o0f6uKnNCl49Bw-1700123422-0-AfMU03CefgJ42XIlvD5Fpt7CbTsrqfF3pgypsRbdsmiuzSTTImIp65J/OSpBk7OahfgGfHsJcZnI8JppbkYfgbU=; path=/; expires=Thu, 16-Nov-23 09:00:22 GMT; domain=.fortnite.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '826e5f1df86eb7a2-AMS', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400')>

**Comment by LeleDerGrasshalmi** [comment]
Hey,

The 403 on fortnite.com is normal, you are facing Cloudflare anti bot protection

And the other api, you should remove the dashes

**Comment by Ricoroma** [comment]
hey, sorry for afk. your advice to remove the dashes helped, but i haven't received item instantly, instead i received a json with offerId, accountId and identityId (and details)
i thought that i've seen some endpoint for these, but can'n find it now, can u help please?

and another question: is there endpoint to get info about offer by offerId? i ask because the [Catalog endpoin](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/7e07df501ce8ad7caa05333cba2e14663d72a4f8/Fortnite/Catalog/Catalog.md) provides strange prices (like today for bundles with discount: 
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/63673236/96965028-9614-4383-b04c-fc59df2af7f2)
it looks strange because other api (https://fortnite-api.com) gives the true price: 
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/63673236/6b942600-0d26-4cc8-a345-510e75ee7b04)
)
even though i can make 2 requests to fill my so called TodayShopItems database (to save offerIds and prices) it looks a little wrong

and last question: am i really needed to calculate the final price by using their endpoint (by the way, what is it?) for PurchaseCatalogEntry and GiftCatalogEntry MPC's? can i just use the finalprice (which is normally got in [fortnite-api.com shop endpoint](https://fortnite-api.com/v2/shop/br)

sorry for too many endpoint questions. i really tried search it by myself, but with these ikd what's wrong

**Comment by Ricoroma** [comment]
@LeleDerGrasshalmi

**Comment by LeleDerGrasshalmi** [comment]
Hey @Ricoroma,

1. that redeems the code, but you need to claim the items in fortnite using [this profile operation](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/RedeemRealMoneyPurchases.md)
2. there is no endpoint to get storefront offer info, all info is returned by the storefront api. and the prices are not "weird", thats just how bundles "dynamicbundles" work, price changes based on which items you own
3. there is no way no api to calculate the price for yourself, only for friends (if they dont own the offer)

**Comment by Ricoroma** [comment]
hey again, @LeleDerGrasshalmi 
1. Thatks, but i quite dont understand, what to put in body
`{
    "appStore": "EpicPurchasingService", // e.g. EpicPurchasingService
    "authTokens": [], // Auth Token (Included in the Auth Response or requested using the platformtoken api) - Required for all app Stores expect EpicPurchasingService & SamsungGalaxyAppStore
    "receiptIds": [], // Receipt Ids, if you just want to refresh those
    "refreshType": "ForceCurrent", // Enum: Default, UpdateOfflineAuth, ForceAll, ForceCurrent
    "verifierModeOverride": "DefaultToConfig", // Unknown and DefaultToConfig was used in the request I captured (fn v24.20), but Enum values: OccurrencePrimary, ReceiptOnly, ReceiptPrimary, DefaultToIapVersion, OccurrenceOnly, DefaultToConfig, OccurrenceOnlyRemoveReceipts
    "purchaseCorrelationId": "" // Can be ignored
}`
(im confused because there are no fields that i have ({'offerId': 'f0566d113be44861979f53c7f819d9b8', 'accountId': 'b7b8eb71927e46fbb740552a0a4115f8', 'identityId': 'b7b8eb71927e46fbb740552a0a4115f8', 'details': [{'entitlementId': 'fc1194a08b174a5fab6494062f7c5d2e', 'entitlementName': 'FN_Cavern_4', 'itemId': 'f9d58d2291764b5c9c986cbcfb26d2f8', 'namespace': 'fn', 'country': 'RU'}]})
shouldnt i use [Fortnite/MCP/operations/ActivateConsumable.md](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/ActivateConsumable.md) endpoint? at least i see key itemId here
2. sad but i'm also in confusion here. as i can see on the first image (last line) param 'alreadyOwned...' is 1200, but i don't have it.  so i don't understand, how should i calculate it... sum all params 'alreadyOwned' and minus discount? 
3.  alright i got it, but what is that endpoint for friend? finalPrice from https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/7e07df501ce8ad7caa05333cba2e14663d72a4f8/Fortnite/Catalog/GiftEligibility.md?

**Comment by LeleDerGrasshalmi** [comment]
1. these fields have nothing todo with the code redeem response
2. you only count items not owned minus discount
3. yes that endpoint for friends

**Comment by Ricoroma** [comment]
1. well so how will the FN understand, what do i want to activate? do you mean that i should just call that mcp and all be ok? (i didn't understand, what endpoint and body is correct)
2. **you only count items not owned minus discount** you mean, comparing bundle to query profile?
3. thanks a lot, at least one thing i've understood☠️

**Comment by LeleDerGrasshalmi** [comment]
1. it will activate everything based on your input (payload), which by default claims everything thats unclaimed.
2. you surely need to know what items you own to calculate the price

**Comment by Ricoroma** [comment]
1. That worked! very grateful! one more thing: what endpoint can check the code? i've seen POSA check, but as you said, it throws a capcha
2. well i think i got the point. thanks a lot, u really saved me

**Comment by LeleDerGrasshalmi** [comment]
until i document the code redemption service you can just use graphql, just check the traffic with fiddler when trying to redeem a code (can be invalid) in the launcher

**Comment by LeleDerGrasshalmi** [comment]
or actually, heres the graphql request

this needs account launcher authentication.
POST `https://graphql.epicgames.com/graphql`
```json
{
    "query": "query CodeRedemptionQuery($code: String!, $locale: String = \"en\") {\r\n    CodeRedemption {\r\n        evaluateCode(codeId: $code locale: $locale) {\r\n            # bool\r\n            success\r\n            # OfferDetails\r\n            data {\r\n                # String\r\n                offerId\r\n                # String\r\n                namespace\r\n                # String\r\n                title\r\n                # String\r\n                description\r\n                # String\r\n                image\r\n                # String\r\n                eulaIds\r\n                # String\r\n                entitlementName\r\n                # String\r\n                codeUseId\r\n                # String\r\n            }\r\n        }\r\n    }\r\n}",
    "variables": {
        "code": "AAAA",
        "locale": "de"
    }
}
```
as always, code without dashes.

**Comment by Ricoroma** [comment]
alright thanks, i'll try it 
gn

**Comment by LeleDerGrasshalmi** [comment]
closing because completec
