### ISSUE TITLE
Global Service - Profile: Get Profiles

### ISSUE THREAD

**Issue by fowummmmm** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#196]
I keep getting an authorization error while using Global Service - Profile: Get Profiles

Array ( [message] => authentication failed [type] => Unauthorized [stackTrace] => Array ( ) [causes] => Array ( ) [code] => 0 )

**Comment by LeleDerGrasshalmi** [comment]
What kind of token type to you use? It requires the use of eg1 tokens

**Comment by fowummmmm** [comment]
I figured that out, now when I'm doing the namespace and it is saying this: "message":"namespace is not supported"
"type":"MCPNamespaceNotFoundException"

**Comment by LeleDerGrasshalmi** [comment]
You need to use the namespace mentioned in the docs

**Comment by fowummmmm** [comment]
I used the Fortnite namespace, I still get the same result.

**Comment by LeleDerGrasshalmi** [comment]
Could you please send the plain http request message?
(redact the jwt)

**Comment by LeleDerGrasshalmi** [comment]
closing because user did not anwser

**Comment by fowummmmm** [comment]
I still have not figured it out. This is all I am getting. {
    "message": "authentication failed",
    "type": "Unauthorized",
    "stackTrace": [],
    "causes": [],
    "code": 0
}

**Comment by fowummmmm** [comment]
?
