### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by malsvn** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#198]
Please remove the `QueryPublicProfile` MCP operation or at least fix it.
It now requires special permissions, permissions that can only be obtained by Epic employers

**Comment by LeleDerGrasshalmi** [comment]
Don't know what you are doing, works for me without any issues...

**Comment by LeleDerGrasshalmi** [comment]
it was never broken

**Comment by LeleDerGrasshalmi** [comment]
and?
thats has nothing todo with the operation
