### ISSUE TITLE
How to get store item pic

### ISSUE THREAD

**Issue by Ricoroma** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#203]
Hello again

during last 30 days i was using side api (fortnite-api.com) for checking everyday storefronts and all was good, until today:
for some reason, now there are some store items (today 20), such as car kits and songs, that are not presented in that api.

so the only way to find info about them is [Fortnite/Catalog](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/Catalog/Catalog.md)
but there are no links to images, only DisplayAssets, so i really don't know, how to get picture from them, so i'm asking your help in this, pls

(note: i haven't registered an EpicGames Dev organization, is it possible without it?)

**Comment by LeleDerGrasshalmi** [comment]
gamefiles

**Comment by Ricoroma** [comment]
and where can i download it?

**Comment by LeleDerGrasshalmi** [comment]
you need to parse your fortnite gamefiles

**Comment by Ricoroma** [comment]
ahh interesting but not usable, thanks

**Comment by Ricoroma** [comment]
i had 1 more question: is it any endpoint, where i can find info about how many gifts can i share today? (0-5)
i found only that in common_core queryProfile i can see all gifts that i've sent with sending date and time, so i can count it with code. but this way seems to me like a crutch, isn't it?

**Comment by LeleDerGrasshalmi** [comment]
thats what you need todo, but only include gifts sent in the last 24h
