### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by Ricoroma** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#206]
Hello. I've written full working authorization by device_id Mechanism, but sometimes after updating access token account starts getting 401 and 403 codes (especially 403)
Do you know, why does it happen? 
![Screenshot_20231217_000737_com microsoft rdc androidx_edit_91152354362131](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/63673236/497e8082-c488-409d-a9d7-4aa6e77188d7)

**Comment by LeleDerGrasshalmi** [comment]
the account needs to have fn access (started it once)
the account you are using hasnt done that once, thats why you get the `missing_action` error

**Comment by Ricoroma** [comment]
Well interesting, cause that acc definitely has some v-bucks and skins on it. Moreover, it was used in my script for gifting previously (successfully)
I don't think that it misses fortnite

**Comment by Ricoroma** [comment]
I just noticed that acc on screen might not be used for that
But just now ive encountered that error again. And i noticed other errror
Is current mistake caused by owning this skin? 
![Screenshot_20231217_145743](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/63673236/54c6e0ba-10d2-4422-8d5b-ba2059cc97db)

**Comment by LeleDerGrasshalmi** [comment]
could you please include proper requests with responses.

**Comment by Ricoroma** [comment]
Sorry, thats all i have. I can only say, that dicts in shell {} and {offer_id....} are given params (data). So link to post is in client response and given params are above it. Also don't look at tracebacks, they are about other. Im asking about purchase_not_allowed (account has v-bucks more than 1500)

**Comment by LeleDerGrasshalmi** [comment]
maybe look at the response body, that has details...

**Comment by Ricoroma** [comment]
Yeah i saw it and that's exactly what I'm asking.  Is purchase_not_allowed being caused by  by owning this skin?

**Comment by LeleDerGrasshalmi** [comment]
it can have many reasons, thats why you should look at the response.

**Comment by Ricoroma** [comment]
Well response that i see on screenshot has only error_code and error_name
I can't access the json of it

**Comment by LeleDerGrasshalmi** [comment]
then i cannot help you.

**Comment by Ricoroma** [comment]
kk, i understood. i'll make request in test file

**Comment by Ricoroma** [comment]
{'offerId': 'v2:/187fec3a3acbd5747a31c0590107ca84e1eed230e4145c35b61fbe099ffdca9d', 'currency': 'MtxCurrency', 'currencySubType': '', 'expectedTotalPrice': 1500, 'gameContext': '', 'purchaseQuantity': 1}
<ClientResponse(https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/21aaa6a2e3f9413bb35e58c618b007a1/client/PurchaseCatalogEntry?profileId=common_core&rvn=-1) [403 Forbidden]>
<CIMultiDictProxy('Date': 'Sun, 17 Dec 2023 12:36:57 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '517', 'Connection': 'keep-alive', 'X-Epic-Error-Code': '28004', 'X-Epic-Error-Name': 'errors.com.epicgames.modules.gamesubcatalog.purchase_not_allowed', 'X-Epicgames-Mcpversion': 'prod-live Release-28.01-28.01 build 401 cl 30329245', 'X-Epicgames-Profile-Revision': '760', 'X-Epic-Correlation-Id': 'b049c2f6-930c-48fa-a0ee-f825334b1e6e', 'Server': 'fn-gateway')>

{'errorCode': 'errors.com.epicgames.modules.gamesubcatalog.purchase_not_allowed', 'errorMessage': 'Could not purchase catalog offer [VIRTUAL]1 x Satoru Gojo, 1 x Sweet Selection for 1500 MtxCurrency, item AthenaCharacter:character_floodplain x 1 (exceeding the limit of 0)', 'messageVars': ['[VIRTUAL]1 x Satoru Gojo, 1 x Sweet Selection for 1500 MtxCurrency', 'AthenaCharacter:character_floodplain', '1', '0'], 'numericErrorCode': 28004, 'originatingService': 'fortnite', 'intent': 'prod-live'}

well i can't tell the difference

**Comment by LeleDerGrasshalmi** [comment]
so as the `errorMessage` says:
> Could not purchase catalog offer [VIRTUAL]1 x Satoru Gojo, 1 x Sweet Selection for 1500 MtxCurrency, item AthenaCharacter:character_floodplain x 1 (exceeding the limit of 0)

The offer is already owned

**Comment by Ricoroma** [comment]
ok, thanks a lot
