### ISSUE TITLE
question.

### ISSUE THREAD

**Issue by Maloski23** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#213]
I am getting this response: { "errorCode" : "errors.com.epicgames.common.missing_permission", "errorMessage" : "Sorry your login does not posses the permissions 'fortnite:profile:(accountid):commands ALL' needed to perform the requested operation", "messageVars" : [ "fortnite:profile:(accountid):commands", "ALL" ], "numericErrorCode" : 1023, "originatingService" : "fortnite", "intent" : "prod-live" }

I'm not sure how to fix this issue or what I can do to gain access.

**Comment by LeleDerGrasshalmi** [comment]
The fix is using your account id.
You cannot Do These for other accounts

**Comment by LeleDerGrasshalmi** [comment]
closing as stale
