### ISSUE TITLE
quickquestion

### ISSUE THREAD

**Issue by iamhim123thehim** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#214]
I am getting this issue and have no idea why 

I am sending a post request to https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/myaccountidwashere/client/SetMtxPlatform?profileId=athena&rvn

{
    "errorCode": "errors.com.epicgames.modules.profiles.invalid_command",
    "errorMessage": "SetMtxPlatform is not valid on player:profile_athena profiles (athena)",
    "messageVars": [
        "SetMtxPlatform",
        "player:profile_athena",
        "athena"
    ],
    "numericErrorCode": 12801,
    "originatingService": "fortnite",
    "intent": "prod-live"
}

**Comment by iamhim123thehim** [comment]
so i fixed that issue but now i am getting

{
    "errorCode": "errors.com.epicgames.modules.profiles.invalid_payload",
    "errorMessage": "Unable to parse command com.epicgames.fortnite.core.game.commands.mtx.SetMtxPlatform. Could not deserialize payload for com.epicgames.fortnite.core.game.commands.mtx.SetMtxPlatform",
    "messageVars": [
        "com.epicgames.fortnite.core.game.commands.mtx.SetMtxPlatform",
        "Could not deserialize payload for com.epicgames.fortnite.core.game.commands.mtx.SetMtxPlatform"
    ],
    "numericErrorCode": 12806,
    "originatingService": "fortnite",
    "intent": "prod-live"
}

**Comment by LeleDerGrasshalmi** [comment]
errors are clear!

you are sending an invalid payload / body

see [SetMtxPlatform Docs](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/operations/SetMtxPlatform.md)

**Comment by LeleDerGrasshalmi** [comment]
closing as stale

**Comment by LeleDerGrasshalmi** [comment]
closing as stale
