### ISSUE TITLE
Need help retrieving stats

### ISSUE THREAD

**Issue by DAVIDWALMART** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#217]
when i try to retrieve stats with the 'Stats Proxy: User Stats'
i get this error: 
{"errorCode":"errors.com.epicgames.common.missing_permission","errorMessage":"Sorry your login does not posses the permissions 'fortnite:stats READ' needed to perform the requested operation","messageVars":["fortnite:stats","READ"],"numericErrorCode":1023,"originatingService":"statsproxy","intent":"live"}
<Response [403]>

plz help lol

**Comment by DAVIDWALMART** [comment]
btw i already did the OAuth correctly 
authentication works well

**Comment by LeleDerGrasshalmi** [comment]
the error is pretry clear  🤔 

you dont have the permission on the authentication

**Comment by DAVIDWALMART** [comment]
oh, so how do i get authentication?

**Comment by LeleDerGrasshalmi** [comment]
you need authentication with the permission.

fortnite clients have that perm

**Comment by DAVIDWALMART** [comment]
can u please provide me more further details? like do i first need to login by myself through the browser to retrieve an OAuth token with permission?

**Comment by LeleDerGrasshalmi** [comment]
what no.

you just need to authenticate with a client that has the permission.

**Comment by DAVIDWALMART** [comment]
yeah bro but how do i know which client has the permission?

**Comment by LeleDerGrasshalmi** [comment]
> fortnite clients have that perm

**Comment by DAVIDWALMART** [comment]
like how do i retrieve the Basic token thats what i dont understand lol

**Comment by LeleDerGrasshalmi** [comment]
what basic token

**Comment by DAVIDWALMART** [comment]
'Authorization': 'Basic ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ='

like this

**Comment by LeleDerGrasshalmi** [comment]
thats just basic authentication, a very basic concept

**Comment by DAVIDWALMART** [comment]
yeah i am kinda new to it lol so may i kindly ask u the place i need to retrieve it from?

**Comment by LeleDerGrasshalmi** [comment]
everything is in the repo, and this repo is intended or people who know what they are doing

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Token.md
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Clients.md

**Comment by DAVIDWALMART** [comment]
yeah i am learning atm

**Comment by DAVIDWALMART** [comment]
the stuff you sent is what comes after, i need to get the access token that has access to this specific stats, the Basic token auth

**Comment by LeleDerGrasshalmi** [comment]
the basic auth just specifies what client you want to authenticate for

**Comment by DAVIDWALMART** [comment]
exactly 
it gives me the error using a basic auth ive found here

**Comment by LeleDerGrasshalmi** [comment]
you need account authentication for stats

**Comment by DAVIDWALMART** [comment]
howd i do that

**Comment by DAVIDWALMART** [comment]
sorry for being so dumb lol

**Comment by DAVIDWALMART** [comment]
ohhh
i think i got it
