### ISSUE TITLE
BR stats and leaderboards

### ISSUE THREAD

**Issue by ricoroma2** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#219]
hi, i was looking through repo searching endpoints for BR stats and leaderboards. 
All i found is two removed endpoints (https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/ec6b267bca542a2b8804084622721a4bd8ae7c7f/Fortnite/Stats.md and statsleaderboard at the same folder)
So are there such endpoints now?

**Comment by LeleDerGrasshalmi** [comment]
Hi,

Check 
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/StatsProxyService

**Comment by ricoroma2** [comment]
thats awesome, thanks. and are there any ways to interpret stats? 
and also, are there endpoints for battlepass stats?

**Comment by LeleDerGrasshalmi** [comment]
well, you can interpret them by grouping my playlist

what do you mean with battle pass stats?
