### ISSUE TITLE
One url doesnt work anymore

### ISSUE THREAD

**Issue by TuNiman1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#220]
this url that i use in my project doesnt work anymore:
https://www.epicgames.com/id/api/exchange/generate
fix pls

**Comment by LeleDerGrasshalmi** [comment]
> this url that i use in my project doesnt work anymore:
https://www.epicgames.com/id/api/exchange/generate
fix pls

What do you mean?

**Comment by TuNiman1** [comment]
its depracted, api has changed most likely

**Comment by TuNiman1** [comment]
doesnt work no more

**Comment by TuNiman1** [comment]
accidently closed

**Comment by LeleDerGrasshalmi** [comment]
That doesn't explain it.
Maybe post what response you get

**Comment by TuNiman1** [comment]
give me one sec

**Comment by TuNiman1** [comment]
it says: 
Cannot POST /id/api/exchange/generate

**Comment by TuNiman1** [comment]
and, i heard on some other forums that its dead by now as well

**Comment by TuNiman1** [comment]
I tried both post and get i am using it as before it worked a week ago and now it just gives me a different error everytime

**Comment by LeleDerGrasshalmi** [comment]
It is removed.

**Comment by TuNiman1** [comment]
wait
is there any alternative api url?

**Comment by LeleDerGrasshalmi** [comment]
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/ExchangeCode/Create.md

**Comment by LeleDerGrasshalmi** [comment]
dude dont open new issues for the same thing...
