### ISSUE TITLE
Global Service - Profile: Get Profiles

### ISSUE THREAD

**Issue by fowummmmm** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#221]
I keep getting this:

{
    "message": "namespace  is not supported",
    "type": "MCPNamespaceNotFoundException",
    "stackTrace": [],
    "causes": [],
    "code": 404
}

I am using an eg1 token. I am using the Fortnite namespace.

**Comment by LeleDerGrasshalmi** [comment]
whatever you are doing, it is wrong.

the error shows you dont even specify any namespace

when you have an invalid ns it would show the following
```json
{
    "message": "namespace {invalidNS} is not supported",
    "type": "MCPNamespaceNotFoundException",
    "stackTrace": [],
    "causes": [],
    "code": 404
}
```

So can you please share your request payload

**Comment by fowummmmm** [comment]
It is sending a request to https://global-profile-service.game-social.epicgames.com/profiles with these parameters: namespace: Fortnite and accountIds: (the account ID). I am not sure what I am doing wrong.

**Comment by LeleDerGrasshalmi** [comment]
send the payload please..

**Comment by fowummmmm** [comment]
I got it working now but I think I am doing something wrong, I am generating eg1 tokens and it looks like this: {"access_token":"(token)","token_type":"bearer","client_id":"3446cd72694c4a4485d81b77adbb2141","internal_client":true,"client_service":"prod-fn","product_id":"prod-fn","application_id":"fghi4567FNFBKFz3E4TROb0bmPS8h1GW"}. I have a Discord bot that generates eg1 tokens for me but it looks different and they work. I am not sure why mine don't work. Do you have any idea?

**Comment by LeleDerGrasshalmi** [comment]
You need account auth, what you sent is client auth.

**Comment by fowummmmm** [comment]
Would I need to use authorization_code?

**Comment by LeleDerGrasshalmi** [comment]
You can, but it doesnt matter which method you are using to authenticate as an account

**Comment by LeleDerGrasshalmi** [comment]
stale
