### ISSUE TITLE
i need the current alternative for the exchange code generate api

### ISSUE THREAD

**Issue by TuNiman1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#223]
the last exchange code generate API url has been depracted a week ago and i am trynna find the latest version of it

**Comment by LeleDerGrasshalmi** [comment]
PLEASE dont open more issues for the same thing or you will be removed

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/ExchangeCode/Create.md

**Comment by TuNiman1** [comment]
okkk bro sorry
