### ISSUE TITLE
PR Points

### ISSUE THREAD

**Issue by ricoroma2** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#232]
hello
i have a few questions
1) does the api provide information about account's PR points?
2) i asked 2 weeks back about StatsProxy and forgot about it, sry. about that issue: i have a misunderstanding on how should i interpret given stats. what i see is some keys which don't give me any information about values (i know nothing about fortnite, sry). so is there anywhere a way to understand, what i am receiving? You said "well, you can interpret them by grouping my playlist", so what is it?

about "what do you mean with battle pass stats?": i meant the BP lvl in each season

**Comment by LeleDerGrasshalmi** [comment]
1. Power Ranking Points do not actually exist from epic games side, they are a virtual thing from fortnite tracker
2. if you dont know nothing about fortnite i dont see why you are doing that stuff

**Comment by ricoroma2** [comment]
i am doing that stuff cause im coder and i have to :(

**Comment by LeleDerGrasshalmi** [comment]
if you look at the structure you can see how you can group it
- stat
- input type
- playlist

**Comment by LeleDerGrasshalmi** [comment]
You are the dev, this repo just documents the endpoints.

I showed you what is contained above

**Comment by ricoroma2** [comment]
ok, thanks anyway
and still a question: where can i find BP levels?

**Comment by LeleDerGrasshalmi** [comment]
in your athena profile
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/Fortnite/MCP/README.md

**Comment by ricoroma2** [comment]
thanks
