### ISSUE TITLE
Account's avatar

### ISSUE THREAD

**Issue by Ricoroma** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#241]
hello/
recently i was thinking about how can i get account's avatar. so i found out that id depends on current skins, but i didn't found it neither in athena or common_core, nor in repo
is there a way to get current skins?

**Comment by Ricoroma** [comment]
also i found EpicGames/GlobalService/Profile/RegionUpdate.md endpoint. does it require to make request with ip from chozen region, or u can just use it whenever you don't have a cooldown?

**Comment by LeleDerGrasshalmi** [comment]
> also i found EpicGames/GlobalService/Profile/RegionUpdate.md endpoint. does it require to make request with ip from chozen region, or u can just use it whenever you don't have a cooldown?

you can just set the version to any of the values listed there.

**Comment by LeleDerGrasshalmi** [comment]
> hello/ recently i was thinking about how can i get account's avatar. so i found out that id depends on current skins, but i didn't found it neither in athena or common_core, nor in repo is there a way to get current skins?

athena profile --> current loadout

**Comment by Ricoroma** [comment]
yep, i found it, but how should i interpret it? i searched in repo for 'loadout', but found only MCP's for clear, set and delete it
so my question is, how from that string in athena profile get a picture

**Comment by LeleDerGrasshalmi** [comment]
gamefiles, or a third party api like https://fortnite-api.com

**Comment by Ricoroma** [comment]
unfortunately that api does not provide anything about it, some as https://fortniteapi.io/
sad but thanks anyway

**Comment by LeleDerGrasshalmi** [comment]
huh? those both provide cosmetics data

**Comment by Ricoroma** [comment]
that one you given privides data by cosmetic_id and im using it, but they offer nothing to do with string loadout
unless there's a way of converting string loadout to cosmetic_ids

**Comment by LeleDerGrasshalmi** [comment]
what "string loadout"?

**Comment by Ricoroma** [comment]
'loadouts': ['adb4ee3e-a32d-4158-9e90-00abfb25956b'], 'loadout_presets': {'CosmeticLoadout:LoadoutSchema_Character': {'0': 'bb2dc815-af34-4b49-b240-aade2eddc0cb', '1': '4068b00e-69ed-4ad4-99b8-5f16699bcc5b'}, 'CosmeticLoadout:LoadoutSchema_Emotes': {'0': 'd8e13769-e2c9-46a5-a725-d06f0e04e3f4'}, 'CosmeticLoadout:LoadoutSchema_Platform': {'0': 'c56808e4-0afa-496f-9942-6f37779c8fb0', '1': '75a820e2-5ba5-4c80-a274-b6c435c33970'}}

this is what i found in athena profile

**Comment by LeleDerGrasshalmi** [comment]
those reference items in the profile, which contain the loadout data

**Comment by Ricoroma** [comment]
oh, i chechked and yes it does
now thanks a lot
