### ISSUE TITLE
Epic Games Login Docs

### ISSUE THREAD

**Issue by HyperionCSharp** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#244]
I didn't see a page for talon or any login endpoints. I have lots of knowledge in this area and would love to write the talon section or make contributions in some other way.

Check out my page if you don't believe.

Thanks

**Comment by LeleDerGrasshalmi** [comment]
Hey,

I have seen your page aswell (great work).

But this repo is explictly not covering email&pass / talon stuff, because its stuff that epic does not want to be public/documented. It just helps account crackers/scammers, which we dont support
