### ISSUE TITLE
how to enable scopes perms

### ISSUE THREAD

**Issue by gromaxbro** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#246]
how to fix this error :

```
{"errorCode":"errors.com.epicgames.common.missing_permission","errorMessage":"Sorry your login does not posses the permissions 'account:public:account READ' needed to perform the requested operation","messageVars":["account:public:account","READ"],"numericErrorCode":1023,"originatingService":"com.epicgames.account.public","intent":"prod"}
```

code :
```import requests


session = requests.Session()
headers = {
    "Content-Type": "application/x-www-form-urlencoded",
    "Authorization": "Basic thsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrsrtsh=="
}

data = {
    "scope":"account:public:account READ",

    "grant_type": "client_credentials", 
    "password": "waofeasf",
    "username": "ggosetsfs"

}

response = session.post("https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token", headers=headers, data=data)

print(response.text)

headers = {
        "Authorization": "bearer "+response.json()["access_token"]
}
uer = session.get(" https://account-public-service-prod.ol.epicgames.com/account/api/public/account/displayName/adwaidmia",headers=headers)


print(uer.text)
```

**Comment by gromaxbro** [comment]
@LeleDerGrasshalmi  sry i am new to this api ik password & "username"/email only require if grand_type is password

but your docs say account:public:account
i dont know how to do that how to authenticate can you help?

**Comment by LeleDerGrasshalmi** [comment]
what client are you using=

**Comment by gromaxbro** [comment]
then how can i access https://account-public-service-prod.ol.epicgames.com/account/api/public/account/displayName

**Comment by LeleDerGrasshalmi** [comment]
> you need account auth, so any grant type expect `client_credentials`

**Comment by gromaxbro** [comment]
@LeleDerGrasshalmi 
thx i will use exchange code then why dont client_creds work tho?

**Comment by Jaren8r** [comment]
fwiw - the client credentials for utDedicatedServer has this permission, so you don't need account auth.

**Comment by gromaxbro** [comment]
alr thx!

**Comment by HyperionCSharp** [comment]
Lele is right you have to pass correct client creds to access the in scope permissions like read/write/create. The grant type password is currently deprecated on public clients and will be full omitted in OAuth2.1 as its function is not needed and its bad practice. You can try to access the dev portal and use the private client creds to pass permissions (must have a verified application on the portal). If nothing works try using exchange code endpoint. Hope this helps a little

sry to budge in lele

**Comment by LeleDerGrasshalmi** [comment]
EOS and actual game clients are 2 different things.

EOS works with scopes & policies. Game/web/normal Clients work with permissions

also i dont see the need of opening this issue again
