### ISSUE TITLE
is there any better way to get auth

### ISSUE THREAD

**Issue by gromaxbro** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#247]
so i am using  "grant_type": "authorization_code", 
but i have to add code manually from browser is there any better way?
and more access code validity.?

**Comment by LeleDerGrasshalmi** [comment]
if you are already replying, then use the resources in this repo.

it is up to date not like mix repo.
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/GrantTypes
