### ISSUE TITLE
Auths

### ISSUE THREAD

**Issue by forum6969** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#252]
Hello, I have had this issue for months now. I have talked with Epic support and tried to figure it out myself but I can't. There is some auth on my account that I cannot find, it puts creator codes in my item shop everyday, it loads me into creative games, it favorites maps right after i unfavorite it and more. It is very annoying and I do not know what to do, I have changed my password, checked for device auths and external auths, I have killed all sessions multiple times, I am not sure what is causing this and I am not sure what else I could do to find what is causing it. Do you have any suggestions of what I could try please?

**Comment by LeleDerGrasshalmi** [comment]
mhh
- are there device auths?
- are there any unknown external auth / third party connections like psn?

**Comment by forum6969** [comment]
No, there are neither of those.

**Comment by LeleDerGrasshalmi** [comment]
Thats weird, thats not really possible then
