### ISSUE TITLE
Fortnite Content API access

### ISSUE THREAD

**Issue by papaformigas** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#253]
Hello, I want to access the Fortnie Content API  but do not know where to start to get into that API.

Can you please tell me all i have to do to access it please.

Many thanks in advance.

**Comment by LeleDerGrasshalmi** [comment]
Hi,

see https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Content/ContentKey.md

**Comment by papaformigas** [comment]
HimLele, thanks for this info, but as i am not aware how this works but know some python knoledge i just want to know how can i access the info of that API. 

Is there in Git Hub any scripts to access this endpoint?

**Comment by LeleDerGrasshalmi** [comment]
hi,

you dont need any authentication/authorization, just request it

**Comment by papaformigas** [comment]
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/17270751/507aa86d-6328-45ee-8646-e70a8c37d838)

**Comment by LeleDerGrasshalmi** [comment]
read the docs and you will be able to use thea pi
