### ISSUE TITLE
GIfting issue

### ISSUE THREAD

**Issue by someone6743** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#257]
When I try to gift and it can gift it has the vbucks and the 2 days so its allowed to gift but when I do it on the api I get this error

{'errorCode': 'errors.com.epicgames.modules.gamesubcatalog.catalog_out_of_date', 'errorMessage': 'Could not find null-MtxCurrency price for catalog item v2:/5e09b7a3a01447b4e39c43c5d85c0ded671a5c5246c7d7ef891fcbf8fd2d5f68', 'messageVars': ['null', 'MtxCurrency', 'v2:/5e09b7a3a01447b4e39c43c5d85c0ded671a5c5246c7d7ef891fcbf8fd2d5f68'], 'numericErrorCode': 28001, 'originatingService': 'fortnite', 'intent': 'prod-live'}

**Comment by Krowe-moh** [comment]
you're trying to gift a offer that's out of the item shop and MtxCurrency doesn't have the amount of vbucks to spend

**Comment by someone6743** [comment]
It’s in the item shop and I got the vbucks

**Comment by LeleDerGrasshalmi** [comment]
Send payload, bust based on the error you entered mtxcurrency in the sub currency field and "null" into the currency field

**Comment by someone6743** [comment]
p = {
    "offerId": "v2:/5e09b7a3a01447b4e39c43c5d85c0ded671a5c5246c7d7ef891fcbf8fd2d5f68",
    "purchaseQuantity": 1,
    "currency": "MtxCurrency",
    "currencySubType": "MtxCurrency",
    "expectedTotalPrice": 800,
    "receiverAccountIds": ["b784c33b0c874146b7e9902a1166924"],
    "giftWrapTemplateId": "",
    "personalMessage": ""
}

i put this as the payload and im getting this error

{'errorCode': 'errors.com.epicgames.modules.gamesubcatalog.catalog_out_of_date', 'errorMessage': 'Could not find MtxCurrency-MtxCurrency price for catalog item v2:/5e09b7a3a01447b4e39c43c5d85c0ded671a5c5246c7d7ef891fcbf8fd2d5f68', 'messageVars': ['MtxCurrency', 'MtxCurrency', 'v2:/5e09b7a3a01447b4e39c43c5d85c0ded671a5c5246c7d7ef891fcbf8fd2d5f68'], 'numericErrorCode': 28001, 'originatingService': 'fortnite', 'intent': 'prod-live'}

**Comment by LeleDerGrasshalmi** [comment]
As the notes say, you put exactly what the offer config has

**Comment by someone6743** [comment]
Ok I also have a question how do I keep the same acc access token because everytime it changes can you give me a docs to look at to keep the access token for longer?

**Comment by someone6743** [comment]
Yes i got it to work thank you!
