### ISSUE TITLE
revision "cleanup_cosmetics_december_2023"

### ISSUE THREAD

**Issue by EmilDabrowski115** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#264]
After the revision:
-"cleanup_cosmetics_december_2023"

 it looks like cosmetics can no longer be found under:
"https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{account_id}/public/QueryPublicProfile?profileId=campaign"

my question is have they been completly removed, cleaned up and moved somewhere else or perhaps the name of the cosmetics have changed, before the names where for example "CID_029_Athena_Commando_F_Halloween", now i cant seem to find these cosmetics anywhere in any endpoint. Im aware that there is a graphql for epic games endpoints, its also worth a try looking around there i assume.

**Comment by LeleDerGrasshalmi** [comment]
cosmetic loadouts have been removed few months ago and are now all stored in athena directly

**Comment by LeleDerGrasshalmi** [comment]
closing as stale
