### ISSUE TITLE
Capture

### ISSUE THREAD

**Issue by Er1onn** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#267]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Hello, i have faced some issues before with my script but i managed to fix that somehow and script is working but the part that i request the capture is not working. Im using this 
api: https://account-public-service-prod03.ol.epicgames.com/account/api/accounts/:accountId/metadata

i dont know anymore what to do if u could help me with a new api cuz maybe im using wrong one!
thank you

**Comment by LeleDerGrasshalmi** [comment]
Hi,

1. This API is not a "Capture"???
2. Maybe show us the request and response you get

**Comment by Er1onn** [comment]
i don't think if u can understand because i am not a language but a script of an app

#capture REQUEST GET "https://account-public-service-prod03.ol.epicgames.com/account/api/accounts/:accountId/metadata" 
  
  HEADER "Authorization: 369ff24b-deab-4d89-b91a-b3b3b4e5828f" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

KEYCHECK 
  KEYCHAIN Success OR 
    KEY "<RESPONSECODE>" Contains "200" 
  KEYCHAIN Custom "FREE" OR 
    KEY "the requested profile didnt play any match yet" 
  KEYCHAIN Failure OR 
    KEY "the requested account does not exist" 
  KEYCHAIN Retry OR 
    KEY "\"status\":500" 
  KEYCHAIN Success OR 
    KEY "the requested account's stats are not public" 

#id PARSE "<SOURCE>" LR "{\"id\":\"" "\",\"" -> VAR "ID" 

PARSE "<SOURCE>" LR "\"battlePass\":{\"level\":" ",\"" CreateEmpty=FALSE -> CAP "Battle Pass Level" 

PARSE "<SOURCE>" LR "\"wins\":" ",\"" CreateEmpty=FALSE -> CAP "Total Wins" 

PARSE "<SOURCE>" LR ",\"kills\":" ",\"" CreateEmpty=FALSE -> CAP "Total Kills" 

PARSE "<SOURCE>" LR "\"matches\":" ",\"" CreateEmpty=FALSE -> CAP "Total Matches" 

PARSE "<SOURCE>" LR "\"lastModified\":\"" "T" CreateEmpty=FALSE -> CAP "Last Login"

**Comment by LeleDerGrasshalmi** [comment]
That's NOT how you authenticate...

You mixed fortnite-api.com stats with epic games unofficial API.

Checkout the getting started guide in this repo
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/AccountService/Authentication#getting-started

**Comment by LeleDerGrasshalmi** [comment]
closing as stale
