### ISSUE TITLE
Unable to proceed with auth

### ISSUE THREAD

**Issue by tposejank** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#272]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

POST

### What is the Request URL?

https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token

### What are your Request Headers (if applicable)?

Authorization: Basic ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=

### What are your Request Payload/Body (if applicable)?

None

### What is the Response Status Code?

400

### What are the Response Headers (if applicable)?

Epic Error Code 1016
errors.com.epicgames.common.oauth.unsupported_grant_type

### What is the Response Content? (if applicable)

```
{
    "errorCode": "errors.com.epicgames.common.oauth.unsupported_grant_type",
    "errorMessage": "Malformed grant type in token request: null",
    "messageVars": [],
    "numericErrorCode": 1016,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Malformed grant type in token request: null",
    "error": "unsupported_grant_type"
}
```

### Additional Context (if applicable)

Hello, i have an issue, I am just trying to obtain an eg1 token at the 
`https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token` URL
I have included the `grant_type` param as `authorization_code`
and the `code` param as the one I obtain from 
`https://www.epicgames.com/id/api/redirect?responseType=code&clientId=ec684b8c687f479fadea3cb2ad83f5c6` (logged in) (fortnitePCGameClient id)

However, I keep getting a "Malformed grant type in token request" on the response
![screenshot from postman](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/81495861/af081ad9-d142-4f5c-a64d-6de7f653ac7d)

I don't know if i am missing any steps
I also tried the `token_type` `eg1` param (described in the [docs](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/AccountService/Authentication#getting-started)) with no success (same error)

Is there something wrong I am doing?
Also, I believe the eg1 token is needed to access `https://events-public-service-live.ol.epicgames.com/` which is what I am trying to do, if it isnt or there is any other recommended way to get this token could you tell me?
Like alternate grant types (I couldnt get device auth working too, the required Auth isnt really described well in [here](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/DeviceCode/Create.md#account-service---auth-create-device-code), as i got this `errors.com.epicgames.common.authentication.authentication_failed` error)

**Comment by LeleDerGrasshalmi** [comment]
Hi,

1. yes the authorization code is sensitive
2. you are supplying the "grant_type" and "code" as a query parameter (in the url)
but they need to be in the "Body" as ``. Check out the example requests how to auth [here](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Token.md#example-request). In postman it's done like this:
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/62852525/dfa5bf32-b6f7-4743-9d6f-b78a62b99d68)
3. regarding eg1 tokens, i would recommend to always use them, you can easily get info about the session without sending a request (to the verify api) and certain apis require you to supply an eg1 token

hope this helps

**Comment by tposejank** [comment]
Yeah, I seem to have fixed the issue
Could you help me with something else?
`https://events-public-service-live.ol.epicgames.com/api/v2/games/FNFestival/leaderboards/season003_54a2b46e-7fc7-4ec9-869f-e011fd8b41a6/54a2b46e-7fc7-4ec9-869f-e011fd8b41a6_Solo_Vocals/scores?accountId=3554e7171c554bdc8b38edb226fe6b0f&fromIndex=0&findTeams=false` I try accessing this

Using the eg1 token (Bearer eg1) i got, this response
`{
    "errorCode": "com.epicgames.api.malformed_data",
    "errorMessage": "com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input\n at [Source: (byte[])\"\"; line: 1, column: 0]"
}`

![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/81495861/159710cb-8d56-4547-abbb-752d90dd7b26)
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/81495861/774fd756-1c45-46d2-990c-157e77bc70c8)
![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/81495861/0360ba98-a048-4686-92b5-8297c7e67eff)

I dont recognize this kind of error

**Comment by LeleDerGrasshalmi** [comment]
you disabled the content length header, so the api doesnt know anything about a body/payload, so it fails to parse it.

![image](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/assets/62852525/c6ddf890-c92a-4ca8-bab2-e71d0f3f1cc1)

**Comment by tposejank** [comment]
Yeah, seem to have got it right after countless attempts! Thanks Lele!

**Comment by tposejank** [comment]
By the way, I can't seem to find docs about the festival leaderboards, would you like if I made some?

**Comment by tposejank** [comment]
Alright
