### ISSUE TITLE
Global Service - Profile: Get Profiles

### ISSUE THREAD

**Issue by Ch1lly5** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#293]
### Issue Checklist

- [x] I have properly named the issue
- [x] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

PUT

### What is the Request URL?

https://global-profile-service.game-social.epicgames.com/profiles

### What are your Request Headers (if applicable)?

headers = {
    "Authorization": "Bearer token (deivce_auth)",
    "Content-Type": "application/json"
}

### What are your Request Payload/Body (if applicable)?

payload = {
    "namespace": "Fortnite",
    "accountIds": [
        "accid"  
    ]
}

### What is the Response Status Code?

Error: 401 - {"message":"authentication failed","type":"Unauthorized","stackTrace":[],"causes":[],"code":0}

### Additional Context (if applicable)

Unsure why its failing, token works for everything else ive tried ecept this endpoint, help appreciated. (Maybe im using a broken client or something? fortniteNewSwitchGameClient)

**Comment by entraptaa** [comment]
Use an EG1 Token instead of the normal switch account token. [Account Service - Auth: Token](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/Token.md#parameters)

**Comment by LeleDerGrasshalmi** [comment]
what entra said
