### ISSUE TITLE
account:public:account UPDATE

### ISSUE THREAD

**Issue by fowummmmm** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#294]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

How do I get a account:public:account UPDATE token?

**Comment by Jaren8r** [comment]
launcherAppClient2 (34a02cf8f4414e29b15921876da36f9a:daafbccc737745039dffe53d94fc76cf) has this permission
