### ISSUE TITLE
HowTo FNAuth

### ISSUE THREAD

**Issue by ninharp** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#308]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

The FNAuth part is still missing. I tried to gather FN Stats but without Auth i didnt get far. I tried also with the hint from the README but only "Sorry the resource you were trying to find could not be found"
If i try it with a normal EOS account auth i only get
"errorMessage": "Sorry your login does not posses the permissions 'fortnite:stats READ' needed to perform the requested operation"

**Comment by LeleDerGrasshalmi** [comment]
You just need Normal fortnight account auth, "FNAuth" is completely unrelated

**Comment by ninharp** [comment]
I used the path you described in EpicGames/AccountService/Authentication/README.md#getting-started and used the Account Authentication with my FN account. Here is what i done so far
1. Make a call to the epicgames.com api redirect and get a authorizationCode for the Account Authenitication
   with client credentials from https://egs.jaren.wtf/
2. Use this code to call /account/api/oauth/token with grant_type=client_credentials and code=<<thecode>>
    and get an access_token for further calls
3. Use this bearer token to make a call to /statsproxy/api/statsv2/account/<<myaccountid>>
   and only get the errror 1023 (missing permission)
   
 What did i do wrong in that path?

**Comment by LeleDerGrasshalmi** [comment]
You are using client auth, you need account auth.

You are using the wrong grant type if you also supply a "code"

**Comment by ninharp** [comment]
You are right, but im already using "authorization_code" as grant_type not client_credentials... i wrote that wrongly ;P

**Comment by LeleDerGrasshalmi** [comment]
I mean , it needs to fortnight auth

**Comment by LeleDerGrasshalmi** [comment]
Pease share some more info

**Comment by ninharp** [comment]
Sure, hope this explains it better

- Choose a client from the webpage https://egs.jaren.wtf/
     for example "launcherAppClient2" with 
     - client id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     - client secret: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
     - 
- Login to epicgames.com

- Make a REST GET call to https://www.epicgames.com/id/api/redirect with parameter
	-  esponseType=code
	-  clientId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

-  From that i retrieve in the incoming json response the authorizationCode
	- authorizationCode: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

- Then i make a REST POST call to https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token with following body parameter
	- grant_type=authorization_code
	- code=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

- In the json response to this call again is a access_token included
	- access_token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

- Then i try to access the fnservice at https://statsproxy-public-service-live.ol.epicgames.com/statsproxy/api/statsv2/account/<<myaccountid>>
	-  As Authorization header is use then this retrieved access_token
	- Authorization: Bearer aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

At this point i got stuck because i get everytime only a 

{
  "errorCode": "errors.com.epicgames.common.missing_permission",
  "errorMessage": "Sorry your login does not posses the permissions 'fortnite:stats READ' needed to perform the requested operation",
  "messageVars": [
    "fortnite:stats",
    "READ"
  ],
  "numericErrorCode": 1023,
  "originatingService": "statsproxy",
  "intent": "live"
}

**Comment by ninharp** [comment]
We can close this issue, after dozens of tries with several clientid/secrets i finally found a pair that worked :) Thanks for your support

**Comment by LeleDerGrasshalmi** [comment]
Ye as I said, you need fortnite auth loll

**Comment by ninharp** [comment]
None of the credentials on https://egs.jaren.wtf/ with fortnite:stats permission were working, Finally your list of client credentials worked
