### ISSUE TITLE
ClaimSubscriptionRewards profile operation doesn't work

### ISSUE THREAD

**Issue by Damnbuoy** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#310]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

POST

### What is the Request URL?

https://fngw-mcp-gc-livefn.ol.epicgames.com/fortnite/api/game/v2/profile/:account_id/client/ClaimSubscriptionRewards

### What is the Response Status Code?

404

### What is the Response Content? (if applicable)

```
{
  "errorCode" : "errors.com.epicgames.fortnite.operation_not_found",
  "errorMessage" : "Operation ClaimSubscriptionRewards not valid",
  "messageVars" : [ "ClaimSubscriptionRewards" ],
  "numericErrorCode" : 16035,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}
```

**Comment by LeleDerGrasshalmi** [comment]
this seems to now be deprecated in favor of [RedeemRealMoneyPurchases](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Service/Game/Profile/Operations/RedeemRealMoneyPurchases.md)

**Comment by Damnbuoy** [comment]
Where do we get the authTokens? Im trying to claim rewards of the crew pack purchased from xbox
