### ISSUE TITLE
Gift eligibility endpoint is not working (OfferId not url encoded)

### ISSUE THREAD

**Issue by Damnbuoy** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#313]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

GET

### What is the Request URL?

https://fngw-mcp-gc-livefn.ol.epicgames.com/fortnite/api/storefront/v2/gift/check_eligibility/recipient/:friendId/offer/:offerId

### What is the Response Status Code?

404

**Comment by BurakYs** [comment]
The endpoint is not removed, you need to uri encode the offer ID

**Comment by Damnbuoy** [comment]
I tried it already. Do I have to remove the v2:/ part?

**Comment by LeleDerGrasshalmi** [comment]
no, that part is important its part of the offer id, you just need to properly url encode the offer id

**Comment by Damnbuoy** [comment]
Thanks it worked, Im silly.

**Comment by beanpython1** [comment]
can you give an example of what its supposed to look like? facing a similar issue
