### ISSUE TITLE
Gifting a friend

### ISSUE THREAD

**Issue by randomnew24** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#316]
**Issue Checklist**
 I have properly named the issue
 I looked in issues/discussions, if my question was previously answered

**What is your question?**

How do you make it possible to gift a friend? I'm using a discord bot and am getting this
error:

Failed to send a gift: Failed to send a gift. Error: Sorry your login does not possess the permissions 'Fortnite:profile:{acc_id}: commands ALL' needed to perform the requested operation

**Comment by LeleDerGrasshalmi** [comment]
you need to use the correct account, YOUR account and fortnite user auth

**Comment by randomnew24** [comment]
Yes, I am signed into my own account and using my Fortnite user auth, but I’m trying to gift a friend by providing their account ID.

**Comment by LeleDerGrasshalmi** [comment]
see? thats incorrect, you need to use your account id, the receiver account ids are in the payload, as specified in [GiftCatalogEntry](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Service/Game/Profile/Operations/GiftCatalogEntry.md)

**Comment by randomnew24** [comment]
ah thank you, it worked.
