### ISSUE TITLE
Gift price

### ISSUE THREAD

**Issue by beanpython1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#319]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Is there another way to get the gift price than using check_eligibility? In the recent update, you cannot gift if someone owns items, so when checking the price it returns {
  "errorCode" : "errors.com.epicgames.modules.gamesubcatalog.receiver_owns_item_from_bundle",
  "errorMessage" : "User already owns items from this bundle.",
  "messageVars" : [ ],
  "numericErrorCode" : 28051,
  "originatingService" : "fortnite",
  "intent" : "prod-live"
}. Just wondering if theres another way which displays the real price of a bundle. :)

**Comment by LeleDerGrasshalmi** [comment]
as the error suggests, you cannot gift the bundle, therefore you cannot get the price for gifting, dont see any issue here, only you making false assumptions

**Comment by beanpython1** [comment]
Sorry, I was not trying to make any assumptions. I was asking a question if there were any other way to see how much something would cost, not exclusive to gifting (although not clear). For example how could I see the price of a bundle after items have been purchased (not gifting - buying). Also, you can still gift bundles perfectly fine through 'giftcatalogentry', which may help you. :)
I apologize if I gave off any negativity.

**Comment by LeleDerGrasshalmi** [comment]
hi,

you need to calculate the price yourself.

you can ask questions in the issues here, or create a discussion in the repo, doesnt really matter.

but:

- issues are mainly for api issues (ex. having an unknown error)
- discussions are mainly for questions

but in the end both will you get you your anwser

**Comment by beanpython1** [comment]
Thank you for your reply. I’ll direct any further questions to the discussions section. :)
