### ISSUE TITLE
How to Retrieve Floor Prices for Bundles?

### ISSUE THREAD

**Issue by randomnew24** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#326]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

I was wondering how I can retrieve the floor prices for bundles using the Fortnite API? I couldn't find much information on it and would appreciate any guidance.

**Comment by BurakYs** [comment]
They are in `<item>.dynamicBundleInfo?.floorPrice` in catalog API response or use 3rd party APIs like fortnite-api.com or fortniteapi.io

**Comment by randomnew24** [comment]
Thanks! Not sure how I missed that. 

I'll use discussions if needed in the future 👍 :)
