### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by ad1txx1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#327]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

This might sound like a dumb question but, in order to create an exchange code (https://account-public-service-prod.ol.epicgames.com/account/api/oauth/exchange) i need in my headers to have a valid EG1~ Bearer. Now i can manually get it intercepting requests when opening the launcher, but i cant seem to find the request that generates that bearer, and i cant find anything in your docs. Can you please tell me if its possible and if so, if its in your docs?

**Comment by ad1txx1** [comment]
or, is it possible to get an exchange token any other way other than /account/api/oauth/exchange ?

**Comment by LeleDerGrasshalmi** [comment]
hi, check the getting started guide, that uses authorization codes for authentication.

you could then use that token to generate an exchange code

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/AccountService/Authentication/README.md#getting-started

**Comment by LeleDerGrasshalmi** [comment]
stale/resolved
