### ISSUE TITLE
api discovery problem

### ISSUE THREAD

**Issue by jose89fcb** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#328]
### Issue Checklist

- [ ] I looked in issues/discussions, if my question was previously anwsered
- [ ] I have properly named the issue

### What is your question?

How does it work to show me the playercounts? the discovery?

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/FN-Discovery-Service/Discovery

I have it like this:

https://fn-service-discovery-live-public.ogs.live.on.epicgames.com/api/v1/discovery/surface/4735ce9132924caf8a5b17789b40f79c?appId=Fortnite

but it doesn't work for me

**Comment by LeleDerGrasshalmi** [comment]
hi, take a look at these docs:

- https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Discovery-Service/Discovery/V2/Main.md
- https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Discovery-Service/Discovery/V2/Page.md

if you encounter an error, please give us details about it (ex. your request and response)

**Comment by jose89fcb** [comment]
> hi, take a look at these docs:
> 
> * https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Discovery-Service/Discovery/V2/Main.md
> * https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Discovery-Service/Discovery/V2/Page.md
> 
> if you encounter an error, please give us details about it (ex. your request and response)

I need the number of players for all Discovery modes playercount
