### ISSUE TITLE
api discovery

### ISSUE THREAD

**Issue by jose89fcb** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#329]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

How do I show the title and image in discovery?

It is shown to me as follows:

```
{
"panels": [
{
"panelName": "Minitiles_Most_Engaging",
"pages": [
{
"results": [
{
"lastVisited": null,
"linkCode": "playlist_juno",
"isFavorite": false,
"globalCCU": 57,
"lockStatus": "UNLOCKED",
"lockStatusReason": "RATING_THRESHOLD",
"isVisible": true
},
```

I would like it to stay like this::

```
{
"linkCode": "playlist_juno",
"playersCount": 52,
"playlistData": {
"name": "LEGO Fortnite",
"type": "BR:Playlist",
"creatorName": "Epic",
"image": "https://cdn2.unrealengine.com/en-fnjn-31-20-lost-isles-discoverplaylisttile-1920x1080-1920x1080-9b2f898f6d4c.jpg"
}
},
```

How could I do it? thank you so much!

**Comment by LeleDerGrasshalmi** [comment]
Hi, you are looking for mnemonic lookup:

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/LinksService/Mnemonic

**Comment by LeleDerGrasshalmi** [comment]
stale
