### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by juancarlosFN** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#332]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Hello, very good, in the discovery api it does not appear
"Campaign"

How do I make it appear?

all maps

```
{
"discovery": [
{
"panelName": "ByEpicAllGames",
"result": [
{
"linkCode": "campaign",
"playersCount": 19755,
"playlistData": {
"name": "Salvar el mundo",
"type": "SubGame",
"creatorName": "Epic",
"image": "https://cdn2.unrealengine.com/stw-1920-1920x1080-5a049ecca449.jpg"
}
}
]
}
]
}
```
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Discovery-Service/Discovery/V1/Page.md

Some packages do not appear in package offers

For example:
True Explorers Mission Pack

It doesn't appear, how do I make it appear? thank you so much

https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/6aa6d6d55d88161e4792b75a1505f0d2a6d32746/Fortnite/Catalog/Offers.md

**Comment by Krowe-moh** [comment]
what are you smoking

**Comment by LeleDerGrasshalmi** [comment]
stale
