### ISSUE TITLE
Tournament matches

### ISSUE THREAD

**Issue by NicolasCassunde** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#340]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Using this api can i see Tournament matches details, leaderboard, overview, event feed...?

For example:

<img width="1277" alt="Captura de Tela 2024-11-09 às 02 18 18" src="https://github.com/user-attachments/assets/3d528b2e-a95b-45f2-99b7-c1ae2dd02bae">
<img width="1283" alt="Captura de Tela 2024-11-09 às 02 20 26" src="https://github.com/user-attachments/assets/18ed244c-5bda-40d2-b9dd-41af4be7d36b">
<img width="1282" alt="Captura de Tela 2024-11-09 às 02 16 52" src="https://github.com/user-attachments/assets/27ac0d35-ff27-4b5f-8eb8-22ff3e72920e">
<img width="1286" alt="Captura de Tela 2024-11-09 às 02 17 08" src="https://github.com/user-attachments/assets/95f1d648-223c-4595-a229-50e3a0bc0eac">

**Comment by Krowe-moh** [comment]
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/EventsService
https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game
