### ISSUE TITLE
refreshing microsoft store entitlements

### ISSUE THREAD

**Issue by Damnbuoy** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#341]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Can this api be used to refresh entitlements of microsoft store?
```
https://fngw-mcp-gc-livefn.ol.epicgames.com/fortnite/api/entitlementCheck
```

**Comment by Krowe-moh** [comment]
it says "entitlementCheck" and it's a get request

**Comment by Damnbuoy** [comment]
> it says "entitlementCheck" and it's a get request

sorry i couldn't find any endpoint except this one for entitlements so i was kinda desperate so didn't notice it lol. Do you know how we can refresh the microsoft store entitlements.Its gonna help me alot.

**Comment by LeleDerGrasshalmi** [comment]
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Service/Game/Profile/Operations/RedeemRealMoneyPurchases.md

you need xbox authentication

**Comment by Damnbuoy** [comment]
thanks alot
