### ISSUE TITLE
Hosted website version of this repo

### ISSUE THREAD

**Issue by simplyzetax** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#344]
Hey,

I own the domain **athena.wiki** and thought it might be a good idea to a create website version of this repo for the public. If you want, I can create some DNS records that point to a potential Github pages site for this repo, or with your permission, I would create a forked version of this project and host the website that way. Let me know what you think. It could also attract new developers to this project who could perhaps contribute

**Comment by LeleDerGrasshalmi** [comment]
I have though about this previously (and even had this repo setup for github pages), but this is currently not planned

**Comment by LeleDerGrasshalmi** [comment]
and "for the public" - if you are searching for docs, and know how to use google, then you will find this repo regardless.

![image](https://github.com/user-attachments/assets/f778004c-eab5-4ef9-a355-f995d76c1f9f)
