### ISSUE TITLE
Team Account Name Leaderboard

### ISSUE THREAD

**Issue by NicolasCassunde** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#345]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

how can i retrieve the team account name?
![Captura_de_Tela_2024-11-09_as_23](https://github.com/user-attachments/assets/f623818c-328c-47ac-817f-2b58a538e77d)

**Comment by LeleDerGrasshalmi** [comment]
you could just use the frontend api, that returns the name directly

`https://www.fortnite.com/competitive/api/leaderboard/:eventId/:eventWindowId/false`

e.g. `https://www.fortnite.com/competitive/api/leaderboard/epicgames_S31_SoloVictoryCashCup_EU/S31_SoloVictoryCashCup_Event5Round1_EU/false`

![image](https://github.com/user-attachments/assets/575bb2ee-5cb2-4a99-803c-613df0696a66)
