### ISSUE TITLE
Purchasing the battle pass/levels

### ISSUE THREAD

**Issue by beanpython1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#346]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Hello,

Is there a simple endpoint to purchase the battle pass and/or levels?

Thanks. :)

**Comment by LeleDerGrasshalmi** [comment]
PurchaseCatalogEntry profile operation:

<https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/FN-Service/Game/Profile/Operations/PurchaseCatalogEntry.md>
