### ISSUE TITLE
SetCosmeticLockerSlot Doesnt work

### ISSUE THREAD

**Issue by ironweb10** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#347]
### Issue Checklist

- [x] I have properly named the issue
- [x] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

GET

### What is the Request URL?

https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/${accountId}/client/SetCosmeticLockerSlot?profileId=athena&rvn=-1

### What are your Request Headers (if applicable)?

headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${token}`
                    }

### What are your Request Payload/Body (if applicable)?

Is a secret

### What is the Response Status Code?

404

### What is the Response Content? (if applicable)

  _header: 'POST /fortnite/api/game/v2/profile/hola/client/SetCosmeticLockerSlots?profileId=athena&rvn=-1 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer hola\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Content-Length: 354\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: fortnite-public-service-prod11.ol.epicgames.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/fortnite/api/game/v2/profile/hola/client/SetCosmeticLockerSlots?profileId=athena&rvn=-1',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'fortnite-public-service-prod11.ol.epicgames.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      errorCode: 'errors.com.epicgames.bad_request',
      errorMessage: 'Disabled locker command SetCosmeticLockerSlots is not allowed',
      numericErrorCode: 1001,
      originatingService: 'fortnite',
      intent: 'prod-live'
    }
  },
  status: 400
}

**Comment by LeleDerGrasshalmi** [comment]
locker loadouts is not done via the profile operations anymore, the new eos locker service has not yet been publicy documented, i will work on that soon

**Comment by ironweb10** [comment]
Ok
