### ISSUE TITLE
Browse Featured Category Collection Data

### ISSUE THREAD

**Issue by BobC0728** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#353]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Epic changed Discovery/Browse in the last couple weeks.  They added some new sections at the the top of the Browse category with sub-categories in those.  I don't see that data in the V2 Discovery API in either the FrontEnd or Browse Surface.  Am I looking at it wrong or it needs to be added?

**Comment by LeleDerGrasshalmi** [comment]
Hi @BobC0728,

These sub-categories are referenced via "Reference" Mnemonics.

![image](https://github.com/user-attachments/assets/de3e0c07-bb26-4115-bbf6-a305062dcaca)

See [Bulk Mnemonic Lookup](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/EpicGames/LinksService/Mnemonic/InfoBulk.md)

**Comment by LeleDerGrasshalmi** [comment]
stale
