### ISSUE TITLE
how to get the playtime of a certain game

### ISSUE THREAD

**Issue by prtolem** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#358]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

I don't understand how to get information about playtime. 
I found one issue related with mine (https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/issues/33), but it did not help me because when requesting GraphQL without authorization, I was given the error "Request failed with status code 401", and with authorization just 500 http code.

**Comment by prtolem** [comment]
I saw it (https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/LibraryService/Playtime) but it didn't work for me because my client_id doesn't output the permission "library: public: {AccountId}: playtime: all READ". Is there another client_id that supports all the features of "fortniteNewSwitchGameClient" and complements "library:"?

**Comment by entraptaa** [comment]
Requires the [Launcher Token](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/fe04e711fdb09980e75ce57d4b3c438bcc23127b/EpicGames/AccountService/Authentication/Clients.md).

**Comment by LeleDerGrasshalmi** [comment]
what @entraptaa said. the library service playtime apis are what you are looking for, they need launcher account authentication (`launcherAppClient2`)
