### ISSUE TITLE
Replacement for fortniteIOSGameClient

### ISSUE THREAD

**Issue by tposejank** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#365]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

fortniteIOSGameClient has recently been disabled, rendering device auth and other useful grants dead for bots which use this client... which client do you recommend?

**Comment by LeleDerGrasshalmi** [comment]
you could use the android client:

`fortniteAndroidGameClient`
Id: `3f69e56c7649492c8cc29f1af08a8a12`
Secret: `b51ee9cb12234f50a69efa67ef53812e`
