### ISSUE TITLE
Game Status

### ISSUE THREAD

**Issue by beanpython1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#368]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Any endpoint that lets you toggle your status (e.g. Online/Away)?
I have been using Fiddler but can't see anything that relates to it :(. I am wanting to create a 'custom' status when offline, similar to the Dub bot.

**Comment by LeleDerGrasshalmi** [comment]
Status and stuff is done via XMPP.

**Comment by LeleDerGrasshalmi** [comment]
stale
