### ISSUE TITLE
Winterfest Openings

### ISSUE THREAD

**Issue by beanpython1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#372]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Hello,
I am using the UnlockRewardNode to open up winterfest presents, and the request goes through as status 200, but it doesn't claim the node. I tried a few more times and discovered it only works when the game is opened with the account. 

Is there a bypass or any explanation?
Thank you.

**Comment by beanpython1** [comment]
POST /fortnite/api/game/v2/profile/REDACTED/client/UnlockRewardNode?profileId=athena HTTP/1.1
Host: fortnite-public-service-prod11.ol.epicgames.com
Authorization: bearer REDACTED
User-Agent: Fortnite/++Fortnite+Release-33.11-CL-38773622 Windows/10.0.26120.1.768.64bit
Content-Type: application/json
Content-Length: 118

{
    "nodeId": "ERG.Node.A.6",
    "rewardGraphId": "bfae149c-19b5-4aed-aff0-de3cf3e57919",
    "rewardCfg": ""
}

**Comment by beanpython1** [comment]
FIXED!

I had to use an exchange token created by the Launcher client ID.

**Comment by beanpython1** [comment]
Despite thinking I fixed it, it is still happening.

Python code: url =

```f"https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{account_id}/client/UnlockRewardNode?profileId=athena"
                headers = {
                    "Authorization": f"Bearer {access_token}"
                }
                body = {
                    "nodeId": str(selected_key),
                    "rewardGraphId": str(reward_graph),
                    "rewardCfg": ""
                }

                response = requests.post(url, headers=headers, json=body)```

The json is: 
```{'nodeId': 'ERG.Node.A.7', 'rewardGraphId': '1d534095-e160-4488-956a-4602519a8989', 'rewardCfg': ''}```

Any help would be greatly appreciated. Thanks :)

**Comment by LeleDerGrasshalmi** [comment]
you unlock one reward node each day, if you dont have any left, you wont get the reward nodes rewards

**Comment by beanpython1** [comment]
I have 2 nodes left today. It works fine if I open in-game.

**Comment by beanpython1** [comment]
Fixed for real this time, just needed to refresh ClientQuestLogin.
