### ISSUE TITLE
Accept EULA

### ISSUE THREAD

**Issue by beanpython1** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#373]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

Does anyone know if there is an endpoint that accepts the Epic Games (not FN) EULA?

Using network logs I have found "https://www.epicgames.com/id/api/corrective/eula", but it always says unauthorized.

**Comment by LeleDerGrasshalmi** [comment]
Hi, you are facing the `EULA_ACCEPTANCE` corrective action, please take a look at [this] endpoint, this needs the continuation token and accepts the EULA. 

the plain eula endpoints will be documented in this repo eventually

**Comment by beanpython1** [comment]
Thank you so much. 🙂
