### ISSUE TITLE
What is the difference between the new Aerial Assault Trooper and the old one?

### ISSUE THREAD

**Issue by prtolem** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#378]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is your question?

I have a problem with the difference between two skins: OG Aerial Assault Trooper and Aerial Assault Trooper. How can they be distinguished using QueryProfile output?

**Comment by simulpingus** [comment]
if creation_time is null, it's og

**Comment by prtolem** [comment]
thanks
