### ISSUE TITLE
I want to get Power level in STW(save the world) of my self how i can do it? what the api endpoint to get this?

### ISSUE THREAD

**Issue by Nakik** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#68]

**Comment by LeleDerGrasshalmi** [comment]
You need to calculate it yourself.

But you can take a look how fnbr.js calculates the powerlevel here
https://github.com/fnbrjs/fnbr.js/blob/master/src/structures/stw/STWProfile.ts#L237
