### ISSUE TITLE
missing operation

### ISSUE THREAD

**Issue by pippococaina** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#93]
RespecUpgrades, used to reset upgrade points (not research) campaign, no body

**Comment by LeleDerGrasshalmi** [comment]
Then:
1. Fork
2. Add the Operation
3. Create a PR (NOT A ISSUE)

**Comment by pippococaina** [comment]
done, sorry

**Comment by LeleDerGrasshalmi** [comment]
Merged
